<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Anexos | “Elementos de Estadística Inferencial con R”</title>
  <meta name="description" content="Anexos | “Elementos de Estadística Inferencial con R”" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Anexos | “Elementos de Estadística Inferencial con R”" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Anexos | “Elementos de Estadística Inferencial con R”" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="referencias.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="introduccion.html"><a href="introduccion.html"><i class="fa fa-check"></i>Introduccion</a></li>
<li class="chapter" data-level="1" data-path="cargar-chunks.html"><a href="cargar-chunks.html"><i class="fa fa-check"></i><b>1</b> Cargar Chunks</a></li>
<li class="chapter" data-level="2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html"><i class="fa fa-check"></i><b>2</b> I Parte: Casos para una poblacion</a>
<ul>
<li class="chapter" data-level="2.1" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#simulacion-de-intervalos-de-confianza"><i class="fa fa-check"></i><b>2.1</b> Simulacion de Intervalos de Confianza</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#método-de-simulacion-ejemplo-1"><i class="fa fa-check"></i><b>2.1.1</b> Método de simulacion: Ejemplo 1</a></li>
<li class="chapter" data-level="2.1.2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#método-de-simulación-ejemplo-2"><i class="fa fa-check"></i><b>2.1.2</b> Método de simulación: Ejemplo 2</a></li>
<li class="chapter" data-level="2.1.3" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#experimento-con-la-confianza"><i class="fa fa-check"></i><b>2.1.3</b> Experimento con la “Confianza”</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#intervalos-de-confianza-para-el-parameto-p"><i class="fa fa-check"></i><b>2.2</b> Intervalos de confianza para el parameto p</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#método-exacto-o-de-clopper-pearson"><i class="fa fa-check"></i><b>2.2.1</b> Método “exacto” o de Clopper-Pearson</a></li>
<li class="chapter" data-level="2.2.2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#metodo-de-wilson"><i class="fa fa-check"></i><b>2.2.2</b> Metodo de Wilson</a></li>
<li class="chapter" data-level="2.2.3" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#metodo-de-laplace"><i class="fa fa-check"></i><b>2.2.3</b> Metodo de Laplace</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#intervalo-de-confianza-para-la-varianza-de-una-poblacion-normal"><i class="fa fa-check"></i><b>2.3</b> Intervalo de confianza para la varianza de una poblacion normal</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html"><i class="fa fa-check"></i><b>3</b> II Parte: Casos con dos poblaciones</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html#diferencia-de-promedios"><i class="fa fa-check"></i><b>3.1</b> Diferencia de Promedios</a></li>
<li class="chapter" data-level="3.2" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html#cociente-de-varianzas"><i class="fa fa-check"></i><b>3.2</b> Cociente de varianzas</a></li>
<li class="chapter" data-level="3.3" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html#diferencia-de-proporciones"><i class="fa fa-check"></i><b>3.3</b> Diferencia de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html"><i class="fa fa-check"></i><b>4</b> Pruebas de hipotesis para una poblacion</a>
<ul>
<li class="chapter" data-level="4.1" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#prueba-de-hipotesis-para-micro"><i class="fa fa-check"></i><b>4.1</b> Prueba de hipotesis para Micro</a></li>
<li class="chapter" data-level="4.2" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#prueba-de-hipotesis-para-p"><i class="fa fa-check"></i><b>4.2</b> Prueba de hipotesis para p</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#muestas-pequeñas"><i class="fa fa-check"></i><b>4.2.1</b> Muestas Pequeñas</a></li>
<li class="chapter" data-level="4.2.2" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#muestas-grandes"><i class="fa fa-check"></i><b>4.2.2</b> Muestas Grandes</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#prueba-de-hipotesis-para-sigma-de-una-variable-aleatoria-con-comportamiento-normal"><i class="fa fa-check"></i><b>4.3</b> Prueba de hipotesis para sigma de una variable aleatoria con comportamiento normal</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html"><i class="fa fa-check"></i><b>5</b> Pruebas de hipotesis para dos poblaciones</a>
<ul>
<li class="chapter" data-level="5.1" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#introducción"><i class="fa fa-check"></i><b>5.1</b> Introducción</a></li>
<li class="chapter" data-level="5.2" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#casos-de-dos-poblaciones"><i class="fa fa-check"></i><b>5.2</b> Casos de Dos poblaciones</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#prueba-de-hipotesis-para-dos-medias-poblacionales-mu_1-y-mu_2"><i class="fa fa-check"></i><b>5.2.1</b> Prueba de hipotesis para dos medias poblacionales <span class="math inline">\(\mu_1\)</span> y <span class="math inline">\(\mu_2\)</span></a></li>
<li class="chapter" data-level="5.2.2" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#contraste-para-dos-medias-independientes-en-r-funcion-t.test"><i class="fa fa-check"></i><b>5.2.2</b> Contraste para dos medias independientes en R: funcion t.test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#prueba-de-hipotesis-para-dos-proporciones-p_1-p_2"><i class="fa fa-check"></i><b>5.3</b> Prueba de hipotesis para dos proporciones <span class="math inline">\(p_1, p_2\)</span></a></li>
<li class="chapter" data-level="5.4" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#prueba-de-hipotesis-para-dos-varianzas-de-sigma_12-sigma_22"><i class="fa fa-check"></i><b>5.4</b> Prueba de hipotesis para dos varianzas de <span class="math inline">\(\sigma_1^2\)</span>, <span class="math inline">\(\sigma_2^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="una-visión-grafica-de-las-pruebas-de-hipotesis.html"><a href="una-visión-grafica-de-las-pruebas-de-hipotesis.html"><i class="fa fa-check"></i><b>6</b> Una visión grafica de las pruebas de hipotesis</a></li>
<li class="chapter" data-level="7" data-path="otras-pruebas-de-hipotesis.html"><a href="otras-pruebas-de-hipotesis.html"><i class="fa fa-check"></i><b>7</b> Otras pruebas de Hipotesis</a></li>
<li class="chapter" data-level="8" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html"><i class="fa fa-check"></i><b>8</b> Prueba de Bondad de Ajuste</a>
<ul>
<li class="chapter" data-level="8.1" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#visualización-de-datos"><i class="fa fa-check"></i><b>8.1</b> Visualización de datos</a></li>
<li class="chapter" data-level="8.2" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#pruebas-formales-de-normalidad"><i class="fa fa-check"></i><b>8.2</b> Pruebas formales de normalidad</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-de-kolmogorov-smirnov-lilliefors-o-k-s-l-test"><i class="fa fa-check"></i><b>8.2.1</b> Test de Kolmogorov-Smirnov-Lilliefors o K-S-L test</a></li>
<li class="chapter" data-level="8.2.2" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-de-normalidad-de-anderson-darling-o-a-d-test"><i class="fa fa-check"></i><b>8.2.2</b> Test de normalidad de Anderson-Darling o A-D test</a></li>
<li class="chapter" data-level="8.2.3" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-de-shapiro-wilks-o-s-w-test"><i class="fa fa-check"></i><b>8.2.3</b> Test de Shapiro-Wilks o S-W test</a></li>
<li class="chapter" data-level="8.2.4" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-omnibus-de-dagostino-pearson"><i class="fa fa-check"></i><b>8.2.4</b> Test omnibus de D’Agostino-Pearson</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="prueba-de-independencia.html"><a href="prueba-de-independencia.html"><i class="fa fa-check"></i><b>9</b> Prueba de Independencia</a></li>
<li class="chapter" data-level="10" data-path="prueba-de-analisis-de-varianza-anova.html"><a href="prueba-de-analisis-de-varianza-anova.html"><i class="fa fa-check"></i><b>10</b> Prueba de Analisis de Varianza (ANOVA)</a></li>
<li class="chapter" data-level="11" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html"><i class="fa fa-check"></i><b>11</b> Regresion y correlacion lineal</a>
<ul>
<li class="chapter" data-level="11.1" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#generando-el-modelo-de-regresion"><i class="fa fa-check"></i><b>11.1</b> Generando el modelo de regresion</a></li>
<li class="chapter" data-level="11.2" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#coeficientes-de-determinación-y-correlacion"><i class="fa fa-check"></i><b>11.2</b> Coeficientes de determinación y correlacion</a></li>
<li class="chapter" data-level="11.3" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#prueba-para-los-residuos"><i class="fa fa-check"></i><b>11.3</b> Prueba para los residuos</a></li>
<li class="chapter" data-level="11.4" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#intervalos-de-confianza-para-la-pendiente-y-el-intercepto"><i class="fa fa-check"></i><b>11.4</b> Intervalos de confianza para la pendiente y el intercepto</a></li>
<li class="chapter" data-level="11.5" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#intervalo-de-confianza-y-prediccion"><i class="fa fa-check"></i><b>11.5</b> Intervalo de confianza y prediccion</a></li>
<li class="chapter" data-level="11.6" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#constraste-de-hipotesis"><i class="fa fa-check"></i><b>11.6</b> Constraste de hipotesis</a></li>
<li class="chapter" data-level="11.7" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#comprobacion-de-las-variabilidades-presentes"><i class="fa fa-check"></i><b>11.7</b> Comprobacion de las variabilidades presentes</a></li>
<li class="chapter" data-level="11.8" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#cuidado-con-el-coeficiente-de-correlacion-y-de-determinación"><i class="fa fa-check"></i><b>11.8</b> Cuidado con el coeficiente de correlacion y de determinación</a></li>
<li class="chapter" data-level="11.9" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#ejemplo-2-correlaciones"><i class="fa fa-check"></i><b>11.9</b> EJEMPLO 2: CORRELACIONES</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="regresion-no-lineal-simple.html"><a href="regresion-no-lineal-simple.html"><i class="fa fa-check"></i><b>12</b> Regresion no lineal simple</a></li>
<li class="chapter" data-level="13" data-path="regresion-lineal-multiple.html"><a href="regresion-lineal-multiple.html"><i class="fa fa-check"></i><b>13</b> Regresion lineal multiple</a>
<ul>
<li class="chapter" data-level="13.1" data-path="regresion-lineal-multiple.html"><a href="regresion-lineal-multiple.html#regresion-lineal-multiple-rlm"><i class="fa fa-check"></i><b>13.1</b> Regresion Lineal Multiple (RLM)</a></li>
<li class="chapter" data-level="13.2" data-path="regresion-lineal-multiple.html"><a href="regresion-lineal-multiple.html#regresión-no-lineal-multiple-rnlm"><i class="fa fa-check"></i><b>13.2</b> Regresión No Lineal Multiple (RNLM)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html"><i class="fa fa-check"></i>Anexos</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#especificaciones-del-proyecto"><i class="fa fa-check"></i>Especificaciones del proyecto</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#i-parte-explicacion-de-los-datos"><i class="fa fa-check"></i>I Parte: Explicacion de los datos</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#ii-parte-analisis-inferencial-ic"><i class="fa fa-check"></i>II Parte: Analisis Inferencial (IC)</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones"><i class="fa fa-check"></i>III Parte: Analisis Inferencial (pruebas de hipotesis de una y dos poblaciones)</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iv-parte-analisis-inferencial-otras-pruebas-de-hipótesis"><i class="fa fa-check"></i>IV Parte: Analisis Inferencial (Otras pruebas de hipótesis)</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#v-parte-analisis-de-regresión"><i class="fa fa-check"></i>V Parte: : Analisis de regresión</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#fases-del-proyecto-y-detalles-de-entrega"><i class="fa fa-check"></i>Fases del proyecto y detalles de entrega</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#especificaciones-del-proyecto-ii-fase"><i class="fa fa-check"></i>Especificaciones del proyecto II Fase</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones-1"><i class="fa fa-check"></i>III parte: Analisis Inferencial (pruebas de hipotesis de una y dos poblaciones)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#espesificaciones-del-proyecto-fase-iii"><i class="fa fa-check"></i>Espesificaciones del proyecto Fase III</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#i-parte-otras-pruebas-de-hipotesis-en-r"><i class="fa fa-check"></i>I Parte: Otras pruebas de hipotesis en R</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-1"><i class="fa fa-check"></i>Caso 1</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-2"><i class="fa fa-check"></i>Caso 2</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-3"><i class="fa fa-check"></i>Caso 3</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-4"><i class="fa fa-check"></i>Caso 4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#ii-parte-modelos-de-regresion-lineal"><i class="fa fa-check"></i>II Parte: Modelos de regresion lineal</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-5"><i class="fa fa-check"></i>Caso 5</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-6"><i class="fa fa-check"></i>Caso 6</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#generacion-de-los-modelos"><i class="fa fa-check"></i>Generacion de los modelos</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#seleccionando-el-mejor-modelo"><i class="fa fa-check"></i>Seleccionando el mejor modelo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iii-parte-modelos-de-regresion-no-lineal"><i class="fa fa-check"></i>III PARTE: Modelos de regresion no lineal</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-7"><i class="fa fa-check"></i>Caso 7</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#solucion-iii-parcial-de-estadistica"><i class="fa fa-check"></i>Solucion III Parcial de Estadistica</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#modelo-0-regresión-lineal-simple"><i class="fa fa-check"></i>Modelo 0: Regresión lineal simple</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#modelo-1-regresion-lineal-multiple-con-todas-las-variables"><i class="fa fa-check"></i>Modelo 1: Regresion lineal multiple con todas las variables</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#modelo-2-regresion-lineal-multiple-con-variables-tv-y-radio"><i class="fa fa-check"></i>Modelo 2: Regresion Lineal Multiple con Variables TV y Radio</a></li>
<li class="chapter" data-level="13.2.1" data-path="anexos.html"><a href="anexos.html#modelo-3-regresion-no-lineal-multiple-con-interacción"><i class="fa fa-check"></i><b>13.2.1</b> Modelo 3: Regresion no Lineal Multiple (Con Interacción)</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">“Elementos de Estadística Inferencial con R”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="anexos" class="section level1 unnumbered hasAnchor">
<h1>Anexos<a href="anexos.html#anexos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="especificaciones-del-proyecto" class="section level2 unnumbered hasAnchor">
<h2>Especificaciones del proyecto<a href="anexos.html#especificaciones-del-proyecto" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Estimado estudiante, el presente documento es una guía para la elaboración del proyecto del curso que tiene <strong>un valor del 50%</strong> sobre la nota final. La guía incluye una descripción de cada una de las partes a realizar y la fecha de entrega. El trabajo serealizará en grupos <strong>máximo de 4 personas</strong>.</p>
</div>
<div id="i-parte-explicacion-de-los-datos" class="section level2 unnumbered hasAnchor">
<h2>I Parte: Explicacion de los datos<a href="anexos.html#i-parte-explicacion-de-los-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para la realización de este proyecto, cada grupo deberá hacer una revisión de varios datasets disponibles en R para uso libre. Se recomiendan las siguientes opciones, pero si el grupo considerar que puede proponer otra base de datos, tiene libertad de hacerlo:</p>
<!-- If someone retake this project or want to modify it and doesn't have any experience in html tags, the <br> tag makes a newline -->
<table>
<colgroup>
<col width="67%" />
<col width="32%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Descripción del dataset</th>
<th align="center">Anotaciones</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Paquete: nycflights13 <br> <a href="https://www.rdocumentation.org/packages/nycflights13/versions/1.0.1" class="uri">https://www.rdocumentation.org/packages/nycflights13/versions/1.0.1</a></td>
<td align="center">Base de datos de vuelos saliendo de New York</td>
</tr>
<tr class="even">
<td align="center">Paquete: Datos <br> <a href="https://www.rdocumentation.org/packages/datos/versions/0.3.0" class="uri">https://www.rdocumentation.org/packages/datos/versions/0.3.0</a></td>
<td align="center">Datos diversos disponibles en la base de R, cuyas variables fueron traducidas al español.</td>
</tr>
<tr class="odd">
<td align="center">Paquete: wooldridge <br> <a href="https://cran.r-project.org/web/packages/wooldridge/wooldridge.pdf" class="uri">https://cran.r-project.org/web/packages/wooldridge/wooldridge.pdf</a></td>
<td align="center">Datos econométricos en inglés, incluye diferentes variables.</td>
</tr>
<tr class="even">
<td align="center">Otros paquetes de R con datasets: <br> <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html" class="uri">https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html</a></td>
<td align="center">Recomendaciones de diferentes paquetes que contienen datasets de uso libre en R.</td>
</tr>
</tbody>
</table>
<hr />
<p>Para cada dataset seleccionado, se debe presentar la siguiente información en el documento escrito:</p>
<p><strong>Dataset</strong>: nombre</p>
<p><strong>Descripción General</strong>:</p>
<p>Describa los aspectos más importantes relacionados con la base de datos a utilizar: lugar, si fue resultado de un trabajo de investigación u otra razón, fechas, lugares, razón que justificó la toma de los datos, etc.</p>
<p>Además, indique en esta sección la composición de la base de datos: tamaño, cantidad de mediciones (filas), cantidad de variables (columnas), describa cada variable (a qué se refiere la medida, unidad de medida usada), si tiene datos faltantes. Para esta sección puede apoyarse en funciones de R como str(), summary(), recursos gráficos entre otros.</p>
<table class="tabla-container">
<tr class="tabla-header">
<th colspan="5">
Resumen de variables seleccionadas
</th>
</tr>
<tr class="check-options">
<th>
<input type="checkbox" id="una-poblacion">
<label for="una-poblacion">Una población</label>
</th>
<th>
<input type="checkbox" id="dos-poblaciones">
<label for="dos-poblaciones">Dos poblaciones</label>
</th>
<th class="sub-col" colspan="2">
<table class="sub-col" style="width: 100%; border-collapse: collapse;">
<tr>
<th>
Población 1
</th>
</tr>
<tr>
<th>
Población 2
</th>
</tr>
</table>
</th>
</tr>
<tr class="tabla-subheader">
<th>
Variables
</th>
<th>
Tipo
</th>
<th colspan="3">
Parámetro por estimar (IC)
</th>
</tr>
<tr>
<td>
Var1
</td>
<td>
Cualitativa
</td>
<td colspan="3">
Proporción, diferencia de proporciones
</td>
</tr>
<tr>
<td>
Var2
</td>
<td>
Cuantitativa
</td>
<td colspan="3">
Media, varianza
</td>
</tr>
<tr>
<td>
Var3
</td>
<td>
Cuantitativa
</td>
<td colspan="3">
Diferencia de medias
</td>
</tr>
<tr>
<td>
Var4
</td>
<td>
Cuantitativa
</td>
<td colspan="3">
Cociente de varianzas
</td>
</tr>
</table>
<p>Tome en cuenta que:
1. Una misma variable puede ser usada en varias pruebas</p>
<ol style="list-style-type: decimal">
<li><p>Si desea, puede usar una variable distinta para cada prueba o variar entreel caso de una o dos poblaciones</p></li>
<li><p>En sustitución de variables cualitativas, puede usar también variablesbinarias que cumplen una función similar (sí o no, 1 o 0, etc)</p></li>
</ol>
</div>
<div id="ii-parte-analisis-inferencial-ic" class="section level2 unnumbered hasAnchor">
<h2>II Parte: Analisis Inferencial (IC)<a href="anexos.html#ii-parte-analisis-inferencial-ic" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Realice intervalos de confianza que involucren una y dos poblaciones (Al menosun IC de: un promedio usando distribución <span class="math inline">\(z\)</span>, un promedio usando distribución <span class="math inline">\(t\)</span>, una proporción, una variancia, una diferencia de promedios usando distribución <span class="math inline">\(z\)</span>, una diferencia de promedios usando distribución <span class="math inline">\(t\)</span>, una diferencia de proporciones y un cociente de variancias).</p></li>
<li><p>Debe indicar las hipótesis asumidas (por ejemplo: la población <span class="math inline">\(X\)</span> se asume quesigue una distribución normal).</p></li>
<li><p>Deben explicar cada uno de los resultados, es decir, las conclusiones obtenidas.En el caso de dos poblaciones recuerde indicar si es posible asumir igualdad de medias, proporciones o varianzas.</p></li>
<li><p>Tome en cuenta que en clase no se estudiaron funciones que permitieran calcular intervalos de confianza para la media o diferencia de medias de los casos donde se conoce la varianza o cuando esta no se conoce, pero el tamaño de la muestra es lo suficientemente grande (n ≥ 30), es decir, los casos en los que el IC se calcula a partir de la distribución normal (Distribución z).</p>
<p>Para trabajar los casos de intervalos de confianza de este tipo (uno para una población y otro para dos poblaciones) deberán investigar sobre cuál o cuáles funciones de R podría utilizar, por lo que se le recomienda estudiar los paquetes <strong>BSDA, stests, PASWR2</strong>.</p>
<p>Para cada caso investigado, deben explicar el formato de la función y aplicarlo en el caso que estén trabajando. Sean claros en indicar si la función aplica solo para una población o para dos poblaciones, podría ser que alguna de ellas tenga usos específicos y otras sean más generales para abordar ambos casos. El siguiente ejemplo muestra una forma de proceder:</p>
<p>Ahora si se automatiza el proceso se puede usar una función de R llamada <code>varTest</code> del paquete <code>EnvStats</code>, cuya estructura sería <code>varTest(X,conf.level)$conf.int</code>.</p>
<ul>
<li><strong>X:</strong> vector que contiene la muestra de datos</li>
<li><strong>conf.level:</strong> nivel de confianza</li>
</ul></li>
</ol>
</div>
<div id="iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones" class="section level2 unnumbered hasAnchor">
<h2>III Parte: Analisis Inferencial (pruebas de hipotesis de una y dos poblaciones)<a href="anexos.html#iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Realice pruebas de hipótesis que involucren una y dos poblaciones (Al menos unapruebade hipótesis de: un promedio, una proporción, una variancia, diferencia depromedios,diferencia de proporciones y cociente de variancias)</p>
<p>Debe indicar las conclusiones obtenidas y también las hipótesis asumidas (por ejemplo,la población X se asume que sigue una distribución normal)</p>
</div>
<div id="iv-parte-analisis-inferencial-otras-pruebas-de-hipótesis" class="section level2 unnumbered hasAnchor">
<h2>IV Parte: Analisis Inferencial (Otras pruebas de hipótesis)<a href="anexos.html#iv-parte-analisis-inferencial-otras-pruebas-de-hipótesis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Realice una Bondad de Ajuste para determinar si una de las variablescuantitativas sigue o no una distribución normal.</li>
<li>Realice una Bondad de Ajuste para determinar si una de las variables cuantitativasigue o no una distribución no normal (escoja una que no sea normal).</li>
<li>Realice una prueba de independencia entre las variables cualitativas de unamisma población.</li>
<li>Realice un ANOVA entre una variable cuantitativa y otra cualitativa de unamismapoblación.</li>
<li>Debe indicar las conclusiones obtenidas</li>
</ol>
</div>
<div id="v-parte-analisis-de-regresión" class="section level2 unnumbered hasAnchor">
<h2>V Parte: : Analisis de regresión<a href="anexos.html#v-parte-analisis-de-regresión" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Realice un análisis de regresión lineal entre las variables cuantitativas de una misma población. (estimación puntual, estimación por intervalo de los parámetros, intervalo de predicción, coeficiente de correlación)</li>
<li>Escoja una regresión <strong>NO lineal</strong> (de las vistas) que se ajuste más para las variables cuantitativas de una misma población. Justifique su escogencia.</li>
<li>Realice un análisis de regresión no lineal escogida entre las variables cuantitativas de una misma población. (estimación puntual, estimación por intervalo de los parámetros, intervalo de predicción, coeficiente de correlación)</li>
</ol>
</div>
<div id="fases-del-proyecto-y-detalles-de-entrega" class="section level2 unnumbered hasAnchor">
<h2>Fases del proyecto y detalles de entrega<a href="anexos.html#fases-del-proyecto-y-detalles-de-entrega" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<table>
<colgroup>
<col width="46%" />
<col width="17%" />
<col width="17%" />
<col width="17%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Fase 1</th>
<th align="center">Fase 2</th>
<th align="center">Fase 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Valor total</td>
<td align="center">15%</td>
<td align="center">15%</td>
<td align="center">20%</td>
</tr>
<tr class="even">
<td align="center">Entrega de informe detallado del análisis realizado que involucra las partes:</td>
<td align="center">Fases I y II Valor 12%</td>
<td align="center">Fase III Valor 12%</td>
<td align="center">Fases IV y V Valor 16%</td>
</tr>
<tr class="odd">
<td align="center">Fecha de entrega del informe:</td>
<td align="center">A más tardar: 17 de abril</td>
<td align="center">A más tardar: 12 de mayo</td>
<td align="center">A más tardar: 2 de junio</td>
</tr>
<tr class="even">
<td align="center">Exposición del trabajo realizado</td>
<td align="center">Valor 3%</td>
<td align="center">3%</td>
<td align="center">4%</td>
</tr>
</tbody>
</table>
<p><strong>Observaciones generales:</strong></p>
<ul>
<li><p>Los datasets y las variables elegidas en la primera fase, podrían mantenerse o cambiarse según los requerimientos en cada una de estas.</p></li>
<li><p>Se dará prioridad a los estudiantes para que conformen sus grupos de trabajo, caso contrario, el profesor asignará los miembros en cada uno de estos. Los grupos se mantendrán invariantes a lo largo del semestre. En caso de que algunos estudiantes se retiren del curso, se valorará la reasignación de los miembros de ese grupo al que pertenecían, siempre justificado en una sobrecarga de trabajo.</p></li>
<li><p>Una vez definidos los grupos, se creará un canal específico para el grupo dentro del equipo del curso en la plataforma Teams. Todos los materiales que se generen como parte de este trabajo, deben concentrarse en este canal.</p></li>
<li><p>Cada grupo deberá crear una Bitácora de minutas de cada una de las reuniones,donde en cada una de ellas aparezca el número de minuta, fecha, presentes, horade inicio, agenda, acuerdos y hora de cierre. Se recomienda que las reuniones sean realizadas en Teams y de requerir ser grabadas, estas quedan automáticamente disponible en la sección se archivos del canal. La primera minuta deberá contener una distribución de tareas por persona y un plan de trabajo que visibilice el alcance de la meta en el plazo.</p></li>
<li><p>El informe debe crearse en <strong>RStudio</strong> y exportarse como documento de <strong>Word</strong>. Este informe debe subirse en la sección de tareas que se creará dentro del canal privado del grupo. <u>No es necesario que se adjunten los documentos Rmd</u>, solo en caso de que estos sean solicitados.</p></li>
<li><p>Todos los cálculos numéricos o estadísticos, estimaciones, gráficos de análisis, trabajo con la base de datos, deberá realizarse en <em>RStudio</em>.</p></li>
<li><p>Sobre la nota del informe en cada fase.</p>
<ul>
<li>El profesor dará una nota inicial del proyecto.</li>
<li>Cada estudiante deberá valorar con un porcentaje el trabajo de cada uno de sus compañeros de equipo y su propio trabajo. Esto se debe realizar mediante un formulario al cuál se le brindará el acceso.</li>
<li><strong>Porcentaje promedio:</strong> <span style="color:#6699ff;">es el promedio ponderado de los porcentajes obtenidos para cada estudiante, la valoración de su trabajo pesará un 60% y las valoraciones dadas por sus compañeros un 40%.</span></li>
<li>La nota de cada estudiante se obtiene sacando el porcentaje promedio obtenido de la nota inicial.</li>
<li><strong>Ejemplo:</strong> suponga que la fase I el grupo 1 estuvo conformado por los estudiantes A, B, C y D:</li>
</ul>
<table border="0" style="border-collapse: collapse;">
<tr>
<th rowspan="2">
</th>
<th rowspan="2">
<p>Nota inicial del informe da por el profesor</p>
</th>
<th colspan="4">
<p>Valoración del trabajo realizado dada por</p>
</th>
<th rowspan="2">
<p>Promedio de valoraciones</p>
</th>
<th rowspan="2">
<p>Nota obtenida del informe de la fase I</p>
</th>
</tr>
<tr>
<th>
<p>A</p>
</th>
<th>
<p>B</p>
</th>
<th>
<p>C</p>
</th>
<th>
<p>D</p>
</th>
</tr>
<tr>
<td>
<p>A</p>
</td>
<td>
<p>90</p>
</td>
<td>
<p>100</p>
</td>
<td>
<p>100</p>
</td>
<td>
<p>100</p>
</td>
<td>
<p>100</p>
</td>
<td>
<p>100</p>
</td>
<td>
<p>90</p>
</td>
</tr>
<tr>
<td>
<p>B</p>
</td>
<td>
<p>90</p>
</td>
<td>
<p>70</p>
</td>
<td>
<p>70</p>
</td>
<td>
<p>70</p>
</td>
<td>
<p>90</p>
</td>
<td>
<p>72.67</p>
</td>
<td>
<p>65.4</p>
</td>
</tr>
<tr>
<td>
<p>C</p>
</td>
<td>
<p>90</p>
</td>
<td>
<p>10</p>
</td>
<td>
<p>60</p>
</td>
<td>
<p>50</p>
</td>
<td>
<p>40</p>
</td>
<td>
<p>26</p>
</td>
<td>
<p>23.4</p>
</td>
</tr>
<tr>
<td>
<p>D</p>
</td>
<td>
<p>90</p>
</td>
<td>
<p>100</p>
</td>
<td>
<p>80</p>
</td>
<td>
<p>90</p>
</td>
<td>
<p>100</p>
</td>
<td>
<p>96</p>
</td>
<td>
<p>86.4</p>
</td>
</tr>
</table></li>
</ul>
<!--Fin de la tabla en HTML-->
<p><strong>Sobre la exposición:</strong></p>
<ul>
<li><p>Las exposiciones se realizan en el horario de clases posterior a la entrega del informe, para lo cual deberá reservar una cita según horario que disponga el profesor. La exposición de la fase 1 y 2 se realizará fuera del horario de clase. La exposición de la fase 3 se realizará en la última clase de la semana 16.</p></li>
<li><p>Deben estar todos los integrantes del grupo, y pueden preparar una presentación no mayor a los 8 minutos.</p></li>
<li><p>Todos los estudiantes deberán exponer de manera equitativa.</p></li>
<li><p>Finalizada la presentación realizarán algunas preguntas teóricas sobre el trabajo realizado. El profesor puede elegir quien de los integrantes del grupo debe responder.</p></li>
<li><p>Desglose de la nota (será la misma para todos los integrantes del grupo):</p>
<ul>
<li><strong>Presentación y manejo del tiempo:</strong> 50%</li>
<li><strong>Respuesta a las preguntas:</strong> 50%</li>
</ul></li>
</ul>
</div>
<div id="especificaciones-del-proyecto-ii-fase" class="section level2 unnumbered hasAnchor">
<h2>Especificaciones del proyecto II Fase<a href="anexos.html#especificaciones-del-proyecto-ii-fase" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La presente guía pretenda dar directrices para la entrega de la segunda fase del proyecto.</p>
<div id="iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones-1" class="section level3 unnumbered hasAnchor">
<h3>III parte: Analisis Inferencial (pruebas de hipotesis de una y dos poblaciones)<a href="anexos.html#iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Para esta segunda entrega, puede utilizar el mismo dataset usado para la primera entrega del proyecto, pero también puede agregar una nuevo dataset si así se prefiere. En caso de agregar nuevos dataset, debe incluir en esta segunda entrega una descripción de este con los mismos elementos que se solicitaron para la entrega anterior.</p></li>
<li><p>Complete el siguiente cuadro indicando el tipo de variable a utilizar y su respectiva prueba de hipótesis. Presente de manera separada el caso de una y dos poblaciones:</p></li>
</ol>
<style type="text/css">
/* Segunda Tabla */
.table-centered {
    width: 100%;
    border-collapse: collapse;
}
.table-centered th, .table-centered td {
    border: 1px solid black;
    padding: 8px;
    text-align: center;  /* Centrar horizontalmente */
    vertical-align: middle;  /* Centrar verticalmente */
}
.table-centered th {
    background-color: #f2f2f2;
}
.header {
    font-weight: bold;
    text-align: center;
}
.checkbox {
    vertical-align: top;
}
</style>
<table class="table-centered">
<tr>
<th colspan="3" class="header">
Resumen de variables seleccionadas
</th>
</tr>
<tr>
<td colspan="3" class="checkbox">
<input type="checkbox"> Una población
</td>
</tr>
<tr>
<th>
Variables
</th>
<th>
Tipo
</th>
<th>
Prueba de hipótesis para:
</th>
</tr>
<tr>
<td>
Var1
</td>
<td>
Cualitativa
</td>
<td>
Proporción, media
</td>
</tr>
<tr>
<td>
Var2
</td>
<td>
Cuantitativa
</td>
<td>
Varianza
</td>
</tr>
</table>
<p><br>
<br></p>
<style type="text/css">
.tabla-container {
    width: 100%;
    max-width: 800px;
    margin: auto;
    border-collapse: collapse;
}

.tabla-container th,
.tabla-container td {
    border: 1px solid black;
    padding: 8px;
    text-align: left;
}

.tabla-header {
    background-color: #003366;
    justify-content: center;
    /* Alinea horizontalmente al centro */
    align-items: center;
    /* Alinea verticalmente al centro */
    color: black;
    text-align: center;
    padding: 10px 0;
    font-size: 18px;
}

.tabla-subheader {
    background-color: #0066cc;
    color: black;
}

.check-options td {
    background-color: white;
    color: black;
    text-align: center;
    font-size: 18px;
}

.check-options input {
    margin-right: 5px;
}

.sub-col td {
    border: none;
    /* Añade esta línea para quitar los bordes */
}
</style>
<table class="tabla-container">
<tr class="tabla-header">
<th colspan="5">
Resumen de variables seleccionadas
</th>
</tr>
<tr class="check-options">
<td colspan="2">
<input type="checkbox" id="dos-poblaciones">
<label for="dos-poblaciones">Dos poblaciones</label>
</td>
<td colspan="3">
<table class="sub-col" style="width: 100%; border-collapse: collapse;">
<tr>
<td>
Población 1
</td>
</tr>
<tr>
<td>
Población 2
</td>
</tr>
</table>
</td>
</tr>
<tr class="tabla-subheader">
<th>
Variables
</th>
<th>
Tipo
</th>
<th colspan="3">
Prueba de hipótesis para:
</th>
</tr>
<tr>
<td>
Var1
</td>
<td>
Cualitativa
</td>
<td colspan="3">
diferencia de proporciones o medias
</td>
</tr>
<tr>
<td>
Var2
</td>
<td>
Cuantitativa
</td>
<td colspan="3">
Cociente de varianzas
</td>
</tr>
</table>
<ol start="3" style="list-style-type: decimal">
<li><p>La segunda entrega deberá incluir todo lo elaborado en la primera entrega con las correcciones respectivas</p></li>
<li><p>Adicionalmente a lo indicado en el punto anterior, deberán incluirse análisis de pruebas de hipótesis para una población (Al menos una prueba de hipótesis de: un promedio con distribución z, un promedio con distribución T, una proporción,una variancia) y dos poblaciones (diferencia depromedios con distribución z, diferencia de promedios con distribución T, diferencia de proporciones y cocientede variancias). En el caso de la prueba de cociente de varianzas, esta puede ser considerada como previo a la prueba T para diferencia de promedios, considerando que esta requiere saber si se puede asumir varianzas iguales o diferentes.</p></li>
<li><p>Para cada caso debe indicar las condiciones asumidas y comprobarlas (si es posible con las herramientas estudiadas hasta ahora). Tome en cuenta las condiciones especiales de los casos de proporciones, varianzas y pruebas T.</p></li>
<li><p>Las hipótesis nulas y alternativas, en cada caso, deben ser planteadas por ustedes dejando de manera explícita en el documento a estas. Además, indique en cada caso si la prueba a utilizar es de cola izquierda, cola derecha, dos colas.</p></li>
<li><p>Para cada caso se debe interpretar la información resumen que provee R en cada una de las pruebas, para eso utilice el siguiente cuadro para el reporte:</p>
<table>
<colgroup>
<col width="35%" />
<col width="64%" />
</colgroup>
<thead>
<tr class="header">
<th><strong>Resumen de la prueba</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Valor observado (escoja entre <span class="math inline">\(t_{obs}, z_{obs}, X_{obs}^2, f_{obs}\)</span>)</td>
<td>____________________________</td>
</tr>
<tr class="even">
<td>Grados de libertad (cuando corresponda)</td>
<td>____________________________</td>
</tr>
<tr class="odd">
<td>Estadístico de prueba (escoja entre <span class="math inline">\(\bar{x}, \hat{p}, s^2, \bar{x_1} \text{ y } \bar{x_2}, \hat{p_1}, \frac{s_1^2}{s_2^1}\)</span>)</td>
<td>____________________________</td>
</tr>
<tr class="even">
<td>Región de aceptación</td>
<td>____________________________</td>
</tr>
<tr class="odd">
<td>Región de rechazo</td>
<td>____________________________</td>
</tr>
<tr class="even">
<td>Nivel de confianza</td>
<td>____________________________</td>
</tr>
</tbody>
</table>
<p><strong>Conclusión</strong></p>
<p>Indíquese <span class="math inline">\(H_0\)</span> es rechazada o no rechaza dado que se encuentre o no evidencia suficiente en contra a partir de lo observado con el valor <span class="math inline">\(P\)</span> y la región de aceptación según corresponda la interpretación en <strong>R</strong>, como fue visto en clases.</p></li>
<li><p>Debe aparecer el código en R utilizado al aplicar cada una de las pruebas, así como las salidas de estos códigos.</p></li>
</ol>
<p><strong>Fases del proyecto y detalles de entrega</strong></p>
<table>
<colgroup>
<col width="46%" />
<col width="18%" />
<col width="18%" />
<col width="18%" />
</colgroup>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Fase 1</th>
<th align="center">Fase 2</th>
<th align="center">Fase 3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Valor total</td>
<td align="center">15%</td>
<td align="center">15%</td>
<td align="center">20%</td>
</tr>
<tr class="even">
<td align="center">Entrega de informe detallado del análisis realizado que involucra las partes:</td>
<td align="center">Partes I y II, valor 12%</td>
<td align="center">Parte III, valor 12%</td>
<td align="center">Parte IV y V, valor 16%</td>
</tr>
<tr class="odd">
<td align="center">Exposición del trabajo realizado</td>
<td align="center">Valor 3%</td>
<td align="center">Valor 3%</td>
<td align="center">Valor 4%</td>
</tr>
</tbody>
</table>
<p><strong>Observaciones generales:</strong></p>
<ul>
<li><p>Cada grupo deberá crear una Bitácora de minutos de cada una de las reuniones, donde en cada una de ellas aparezca el número de minuta, fecha, presentes, hora de inicio, agenda, acuerdos y hora de cierre. La primera minuta deberá contener una distribución de tareas por persona y un plan de trabajo que visibilice el alcance de la meta en el plazo. Se adjuntará una plantilla de minuta, por si desean considerarla como base:</p></li>
<li><p>El informe debe crearse en <strong>RStudio</strong> y exportarse como documento de <strong>Word</strong>. Este informe debe subirse en la sección de tareas que se creará en el grupo general, pero sólo se le dará acceso a las personas que realizaron la primera entrega. <u>No es necesario que se adjunten los documentos Rmd</u>, solo en caso de que estos sean solicitados.</p></li>
<li><p>Todos los cálculos numéricos o estadísticos, estimaciones, gráficos de análisis, trabajo con la base de datos, deberá realizarse en <strong>RStudio</strong>.</p></li>
<li><p>La autoevaluación, coevaluación y exposición, se rigen bajo las mismas reglas explicadas para la primera entrega.</p></li>
</ul>
</div>
</div>
<div id="espesificaciones-del-proyecto-fase-iii" class="section level2 unnumbered hasAnchor">
<h2>Espesificaciones del proyecto Fase III<a href="anexos.html#espesificaciones-del-proyecto-fase-iii" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="i-parte-otras-pruebas-de-hipotesis-en-r" class="section level3 unnumbered hasAnchor">
<h3>I Parte: Otras pruebas de hipotesis en R<a href="anexos.html#i-parte-otras-pruebas-de-hipotesis-en-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>En esta sección se presentarán algunos casos relacionados con pruebas de hipótesis de bondad de ajuste, ANOVA´s e independencia. Deben posterior a la lectura del caso, identificar el tipo de prueba que mejor se adapte a la situación.</p>
</div>
<div id="caso-1" class="section level3 unnumbered hasAnchor">
<h3>Caso 1<a href="anexos.html#caso-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Utilice la base de datos KidsFeet paquete mosaicData como evidencia para para realizar un estudio de normalidad de la longitud del pie (length) de los niños (<strong>B</strong>: boys) es igual que el de las niñas (<strong>G</strong>: girls). Para emitir su conclusión, siga el siguiente proceso:</p>
<ul>
<li><p>Para este ejercicio, explique como la siguiente instrucción permite agrupar los datos para niños y niñas: <code>feetsplit &lt;- split(feet$length,feet$sex)</code></p></li>
<li><p>Para cada datset (niños y niñas), haga un estudio gráfico de la normalidad. Para esto elabore el gráfico que contenga tanto la función de densidad para cada caso como su respectiva curva normal teórica a partir de su media y desviación estándar. ¿Se puede intuir una posible normalidad para los datos?. explique brevemente.</p></li>
<li><p>Para cada dataset (niños y niñas) elabore un gráfico QQ-plot y haga la interpretación en cada caso, desde el punto de vista si es posible asumir normalidad.</p></li>
<li><p>Realice las pruebas formales de normalidad <code>S-W test</code>, <code>A-D test</code>,<code>K-S-L test</code>.</p></li>
<li><p>¿Es posible aplicar D’Agostino-Pearson?. En caso de ser posible, realice la prueba.</p></li>
<li><p>Haga una análisis de la custoris y simetría de los datos usando las funciones respectivas del paquete moments. No es necesario que realice el gráfico tal como se mostró en clases, solo observe los resultados para una posterior interpretación.</p></li>
</ul>
</div>
<div id="caso-2" class="section level3 unnumbered hasAnchor">
<h3>Caso 2<a href="anexos.html#caso-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Realice todo lo solicitado el Caso 1, pero utilizando los datos de biceps de la tabla medidas_cuerpo. Para obtener la base de datos, realice los siguiente:</p>
<ol style="list-style-type: decimal">
<li>Descargue la base de datos desde la url como sigue:</li>
</ol>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="anexos.html#cb347-1" tabindex="-1"></a>url <span class="ot">&lt;-</span></span>
<span id="cb347-2"><a href="anexos.html#cb347-2" tabindex="-1"></a><span class="st">&#39;https://raw.githubusercontent.com/fhernanb/datos/master/medidas_cuerpo&#39;</span></span>
<span id="cb347-3"><a href="anexos.html#cb347-3" tabindex="-1"></a>variable <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">file=</span>url, <span class="at">header=</span>T)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li><p>Recuerde que puede darle el nombre que desee a la variable.</p></li>
<li><p>Analice cada prueba de normalidad como se solicitó en el <strong>Caso 1</strong>, utilizando todos los datos de la varible biceps, <strong>NO</strong> haga separación alguna por sexo u otra categoría en este análisis.</p></li>
</ol>
<p>Una vez realizado todo los cálculos de pruebas de normalidad para los <strong>Casos 1 y 2</strong>, complete la siguiente tabla con la información que corresponda en cada una de las celdas:</p>
</div>
<div id="caso-3" class="section level3 unnumbered hasAnchor">
<h3>Caso 3<a href="anexos.html#caso-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>La siguiente tabla resume los datos de obtenidos de víctimas de crímenes elegidas al azar (según datos del Departamento de Justicia de USA):</p>
<table>
<thead>
<tr class="header">
<th align="center"></th>
<th align="center">Homicidio</th>
<th align="center">Robo</th>
<th align="center">Asalto</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">El criminal era un extraño</td>
<td align="center">12</td>
<td align="center">379</td>
<td align="center">727</td>
</tr>
<tr class="even">
<td align="center">El criminal era un conocido o pariente</td>
<td align="center">39</td>
<td align="center">106</td>
<td align="center">642</td>
</tr>
</tbody>
</table>
<p>Con los datos anteriores, ¿sería posible considerarque el tipo de delito es independiente de la condición del delincuente?, o por el contrario, ¿existe alguna relación entre el tipo de delito con respecto al quien comete el acto? Use un nivel de significancia de 5%.</p>
<p>Además, complete a partir de los resultados de la prueba, lo que se solicita en la siguiente tabla:</p>
</div>
<div id="caso-4" class="section level3 unnumbered hasAnchor">
<h3>Caso 4<a href="anexos.html#caso-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Analice con detenimiento la siguiente situación:</p>
<p>La seguridad de los automóviles se determina mediante diversas pruebas. Una de ellas consiste en hacer chocar un automóvil contra una barrera fija a <span class="math inline">\(35 \textit{ mi/h }\)</span> con un maniquí colocado en el asiento del conductor.</p>
<p>A una de las medidas utilizadas para cuantificar el impacto del choque sobre el conductor se le conoce como <strong>Desaceleración de pecho</strong> y se mide en unidades de fuerza de gravedad (<span class="math inline">\(g\)</span>). Los valores más grandes indican mayores cantidades de desaceleración, las cuáles pueden provocar lesiones graves en los conductores. La siguiente tabla muestra mediciones de desaceleraciones de pecho obtenidas a partir de pruebas de choques de diferentes tipos de vehículos:</p>
<table>
<thead>
<tr class="header">
<th align="center">Autos compactos</th>
<th align="center">Autos medianos</th>
<th align="center">Autos grandes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">44</td>
<td align="center">41</td>
<td align="center">32</td>
</tr>
<tr class="even">
<td align="center">43</td>
<td align="center">49</td>
<td align="center">37</td>
</tr>
<tr class="odd">
<td align="center">44</td>
<td align="center">43</td>
<td align="center">38</td>
</tr>
<tr class="even">
<td align="center">54</td>
<td align="center">41</td>
<td align="center">45</td>
</tr>
<tr class="odd">
<td align="center">38</td>
<td align="center">47</td>
<td align="center">37</td>
</tr>
<tr class="even">
<td align="center">43</td>
<td align="center">44</td>
<td align="center">33</td>
</tr>
<tr class="odd">
<td align="center">42</td>
<td align="center">37</td>
<td align="center">38</td>
</tr>
<tr class="even">
<td align="center">45</td>
<td align="center">34</td>
<td align="center">45</td>
</tr>
<tr class="odd">
<td align="center">50</td>
<td align="center"></td>
<td align="center">43</td>
</tr>
<tr class="even">
<td align="center"></td>
<td align="center"></td>
<td align="center">42</td>
</tr>
</tbody>
</table>
<p>Con los datos anteriores, ¿es posible considerar que el tamaño del automóvil puede variar en cuanto a la seguridad de sus pasajeros o por el contrario, es igualmente riesgoso?. Use un nivel de significancia del 5%.</p>
<ol style="list-style-type: decimal">
<li><p>Con los datos que imprime la prueba,complete la información requerida en la siguiente tabla:</p></li>
<li><p>En caso de detectar alguna diferencia en cuanto a la seguridad que puede brindar al tamaño del vehículo, ¿es posible en cuáles existe una verdadera diferencia significativa?. De ser así, realice la prueba que corresponda e interprete el resultado.</p></li>
</ol>
</div>
</div>
<div id="ii-parte-modelos-de-regresion-lineal" class="section level2 unnumbered hasAnchor">
<h2>II Parte: Modelos de regresion lineal<a href="anexos.html#ii-parte-modelos-de-regresion-lineal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En esta sección se analizán casos relacionados con los modelos de Regresión Lineal Simple (RLS) y múltiple (RLM), así como los modelos de Regresión no Lineal Simple (RNLS)</p>
<div id="caso-5" class="section level3 unnumbered hasAnchor">
<h3>Caso 5<a href="anexos.html#caso-5" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Cargue los datos EdadPesoGrasas.txt como se muestra a continuación:</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="anexos.html#cb348-1" tabindex="-1"></a>grasas <span class="ot">&lt;-</span></span>
<span id="cb348-2"><a href="anexos.html#cb348-2" tabindex="-1"></a><span class="fu">read.table</span>(<span class="st">&#39;http://verso.mat.uam.es/~joser.berrendero/datos/EdadPesoGrasa</span></span>
<span id="cb348-3"><a href="anexos.html#cb348-3" tabindex="-1"></a><span class="st">s.txt&#39;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Para dichos datos, realice lo siguiente:</p>
<ol style="list-style-type: decimal">
<li><p>Elabore un análisis de correlación completo entre todas las variables y haga una interpretación de lo que observa. Debe utilizar al menos un recurso gráfico y uno numérico.</p></li>
<li><p>Seleccione las dos variables con mayor coeficiente de correlación y genere un modelo RLS de mejor ajuste para ambas variables. Defina claramente quién es la variable respuesta y quién la variable explicativa.</p></li>
<li><p>Analice la calidad del modelo generado a partir de su coeficiente de correlación y de determinación.</p></li>
<li><p>Genere un gráfico que muestre tanto los datos de dispersión como la recta de mejor ajuste. Interprete lo que observa en el gráfico.</p></li>
<li><p>Realice la prueba de normalidad para los residuos e indique si se cumple la condición.</p></li>
<li><p>Calcule el intervalo de confianza de 95% para los coeficientes del modelo.</p></li>
<li><p>Para una edad de 27 años, determine un IC de 95% para <span class="math inline">\(\mu_{Y|x=27}\)</span> y un intervalo de predicción para los valores de Y asociados a dicha edad. Interprete el resultado para ambos casos.</p></li>
<li><p>¿Es significativa la linealidad para estas variables?, ¿es posible considerar dependencia lineal entre estas? Haga la prueba de hipótesis correspondiente para responder a estas preguntas.</p></li>
</ol>
</div>
<div id="caso-6" class="section level3 unnumbered hasAnchor">
<h3>Caso 6<a href="anexos.html#caso-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Supóngase que el departamento de ventas de una empresa quiere estudiar la influencia que tiene la publicidad a través de distintos medios de comunicación, sobre el número de ventas de un producto. Se dispone de un conjunto de datos que contiene los ingresos (en millones) conseguido por ventas en 200 regiones, así como la cantidad de presupuesto, también en millones, destinado a anuncios por radio, TV y periódicos en cada una de ellas.</p>
<p>Los datos se encuentran en el archivo DatosVentas.csv.</p>
<p>Para estos datos, realice los siguiente:</p>
<ul>
<li>Instale y cargue las librerías <code>bbmle</code> y <code>DALEX</code></li>
</ul>
</div>
<div id="generacion-de-los-modelos" class="section level3 unnumbered hasAnchor">
<h3>Generacion de los modelos<a href="anexos.html#generacion-de-los-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Genere un primer modelo denominado <code>mod0</code> el cuál será un modelo RLS, usando como variables respuesta ventas y como variables exploratoria a tv. Una vez calculados los coeficientes en <code>R</code> para las variables y el intercepto, escriba la ecuación del modelo estimado.</p></li>
<li><p>Genere, usando la función <code>lm</code> de R, un primer Modelo RLM donde las variables predictoras o exploratorias sean tv, radio y periodico, la variable respuesta ventas. Escriba la ecuación provisional del modelo que se desea determinar. Guarde el modelo en una variable que debe llamar <code>mod1</code></p></li>
</ol>
<p>Una vez calculados los coeficientes en R para las variables y el intercepto, escriba la ecuación del modelo estimado.</p>
<p>De los 4 coeficientes calculados en R, ¿cuáles de ellos son estadísticamente significativos (aportan al modelo) y cuáles no lo son?. Explique su respuesta, apoyándose en los datos del modelo obtenidos en R.</p>
<ol start="3" style="list-style-type: decimal">
<li><p>Seguidamente, genere un segundo Modelo <code>RLM</code> usando nuevamente la función <code>lm</code>, pero en este caso contemple <strong>SOLO</strong> las variables cuyos coeficientes resultaron ser estadísticamente significativos en el análisis anterior. Guarde este modelo en una variable que debe llamar <code>mod2</code>. Según los datos, ¿son todos los coeficiente significativos? Justifique su respuesta.</p></li>
<li><p>Usando los mismo datos, genere un Modelo de RNLM de la forma <span class="math inline">\(\text{ventas} = b_0 + b_1 \text{tv} + b_2 \text{radio} + b_3 \left(\text{tv} * \text{radio} \right)\)</span>. Se recomienda usar nuevamente la función <code>lm</code> y guarde el modelo en una varible que deberá llamar <code>mod3</code>. Una vez que se tengan los datos del modelo, indique si los coeficientes calculados son estadísticamente significativos o no, justificando adecuadamente su respuesta.</p></li>
</ol>
</div>
<div id="seleccionando-el-mejor-modelo" class="section level3 unnumbered hasAnchor">
<h3>Seleccionando el mejor modelo<a href="anexos.html#seleccionando-el-mejor-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para esta sección, deberá seleccionar el mejor modelo entre los 4 ya generados en la I Parte de esta prueba, es decir: <strong>mod0</strong>, <strong>mod1</strong>, <strong>mod2</strong> y <strong>mod3</strong>.</p>
<p>Para hacer una adecuada escogencia, debe utilizar 4 criterios a saber:</p>
<ol style="list-style-type: decimal">
<li><p>Coeficiente de correlación y coeficiente de determinación</p></li>
<li><p>Criterio de Información de Akaike (<strong>AIC</strong>), el cual, representa una medida de la calidad relativa de un modelo estadístico, para un conjunto dado de datos. Como tal, el AIC proporciona un medio para la selección del modelo. <strong>AIC</strong> maneja un trade-off entre la bondad de ajuste del modelo y la complejidad del modelo, basado en el principio de que un mejor modelo debe además de la precisión, ser simple en cuanto a que debe utilizar la menor cantidad de variables predictoras (Principio de parsimonia).</p></li>
<li><p>Los residuales, que están conformados por todas las diferencias entre el valor obtenido en la muestra con respecto al estimado por el modelo. Recuerde que mientras más grande sean los residuales, más se alejan los puntos del modelo y este se vuelve menos confiable.</p></li>
<li><p>Comparación de modelos mediante Análisis de Varianzas, es decir, un ANOVA para los modelos. Para este estudio deberá usar la funciónanova() del <code>paquetestats</code>.</p></li>
</ol>
<p>Una vez definida la ruta, realice lo siguiente:</p>
<ol style="list-style-type: decimal">
<li>Calcule los coefiencientes de correlación y de determinación de los modelos <strong>mod0</strong>, <strong>mod1</strong>, <strong>mod2</strong> y <strong>mod3</strong> y haga una comparación entre estos modelos a partir de este criterio, ¿Cuál de los 3 modelos es mejor?. Explique su escogencia.</li>
</ol>
<p>Esta información deberá ser presentada en la siguiente tabla:</p>
<ol start="2" style="list-style-type: decimal">
<li><p>Tome el modelo 2 (<code>mod2</code>) y explique el significado de los coefiecientes de correlación y de determinación para ese caso.</p></li>
<li><p>Usando la función <code>AICctab</code> del paquete <code>bbmle</code>, calcule los valores del indicador AIC para cada uno de los modelos y con base en ellos, defina el orden de estos de mejor a peor. El criterio que debe usar es <strong>menor AIC, mejor el modelo</strong>. Instrucción para R:</p></li>
</ol>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="anexos.html#cb349-1" tabindex="-1"></a><span class="fu">AICctab</span>(mod1, mod2, mod3, <span class="at">base =</span> T, <span class="at">delta =</span> T, <span class="at">sort =</span> T, <span class="at">weights =</span> T, <span class="at">nobs =</span> <span class="co">#)</span></span></code></pre></div>
<p><em>Nota</em>: debe completar el parámetro nobs (número de observaciones), según la corresponda a la base de datos.</p>
<ol start="4" style="list-style-type: decimal">
<li>El análisis de los residuales se trabajará <strong>solo</strong> con los modelos <code>mod0, mod2 y mod3</code> debido a que el modelo 1 y 2 resultaron ser similares. Para este trabajo debe usar algunas funciones del paquete <code>DALEX</code>. Seguidamente se detallan los pasos a seguir:</li>
</ol>
<p><strong>Cree los Explain Models</strong></p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="anexos.html#cb350-1" tabindex="-1"></a>exp_lm0 <span class="ot">&lt;-</span> <span class="fu">explain</span>(mod0, <span class="at">data =</span> base de datos, <span class="at">label =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">y =</span> variable respuesta)</span>
<span id="cb350-2"><a href="anexos.html#cb350-2" tabindex="-1"></a>exp_lm2 <span class="ot">&lt;-</span> <span class="fu">explain</span>(mod2, <span class="at">data =</span> base de datos, <span class="at">label =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">y =</span> variablerespuesta)</span>
<span id="cb350-3"><a href="anexos.html#cb350-3" tabindex="-1"></a>exp_lm3 <span class="ot">&lt;-</span> <span class="fu">explain</span>(mod3, <span class="at">data =</span> base de datos, <span class="at">label =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">y =</span> variable respuesta)</span></code></pre></div>
<p><strong>Cree los Performance Models</strong> a partir de los Explain Models</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="anexos.html#cb351-1" tabindex="-1"></a>lm0 <span class="ot">&lt;-</span> <span class="fu">model_performance</span>(exp_lm0)</span>
<span id="cb351-2"><a href="anexos.html#cb351-2" tabindex="-1"></a>lm2 <span class="ot">&lt;-</span> <span class="fu">model_performance</span>(exp_lm2)</span>
<span id="cb351-3"><a href="anexos.html#cb351-3" tabindex="-1"></a>lm3 <span class="ot">&lt;-</span> <span class="fu">model_performance</span>(exp_lm3)</span></code></pre></div>
<p><strong>Grafique ambos modelos</strong></p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="anexos.html#cb352-1" tabindex="-1"></a><span class="fu">plot</span>(lm0,lm2, lm3)</span></code></pre></div>
<p>Interprete el gráfico y escoja el mejor modelo, usando el criterio: <strong>curva menor o más baja, es mejor</strong>. Explique a partir del gráfico, por qué este criterio tiene sentido para justificar que un modelo es mejor que otro.</p>
<ol start="5" style="list-style-type: decimal">
<li>Finalmente y como último criterio, realice el análisis de varianza. Para escoger el mejor modelo solamente debe tomar en cuenta el valor de Residual Sum of Squares(<strong>RSS</strong>), donde a menor valor, mejor es el modelo, es decir, los puntos están más ajustados.</li>
</ol>
<p>Considere la siguiente instrucción para realizar este análisis:</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="anexos.html#cb353-1" tabindex="-1"></a><span class="fu">anova</span>(mod0,mod1, mod2, mod3)</span></code></pre></div>
</div>
</div>
<div id="iii-parte-modelos-de-regresion-no-lineal" class="section level2 unnumbered hasAnchor">
<h2>III PARTE: Modelos de regresion no lineal<a href="anexos.html#iii-parte-modelos-de-regresion-no-lineal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="caso-7" class="section level3 unnumbered hasAnchor">
<h3>Caso 7<a href="anexos.html#caso-7" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Para esta sección deberá generar dos modelos de RNLS usando los datos de bones de la base de datos <code>jaws</code>, la cuál contiene información sobre la longitud de la mandíbula de los venados, según la edad.</li>
</ol>
<div class="sourceCode" id="cb354"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb354-1"><a href="anexos.html#cb354-1" tabindex="-1"></a>var <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;nombre.txt&quot;</span>,<span class="at">header=</span>T)</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Luego, construya una gráfico de dispersión para los datos:</li>
</ol>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="anexos.html#cb355-1" tabindex="-1"></a><span class="fu">ggplot</span>(datos,<span class="fu">aes</span>(<span class="at">x =</span> ..., <span class="at">y =</span> ...)) <span class="sc">+</span></span>
<span id="cb355-2"><a href="anexos.html#cb355-2" tabindex="-1"></a> <span class="fu">geom_point</span>()</span>
<span id="cb355-3"><a href="anexos.html#cb355-3" tabindex="-1"></a><span class="co"># en lugar de geom_point(), también puede usar geom_jitter()</span></span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>Usando la función <code>nls()</code> del paquete <code>stats</code>, van a generar un modelo de RNLS de la forma <span class="math inline">\(y = a(1 - e^{-c \cdot x} )\)</span>. A este modelo asígnele el nombre de <code>model1</code>. Use como valores iniciales <strong>a = 120</strong> y <strong>c = 0.064</strong>. Escriba la ecuación del modelo usando los valores para los parámetros obetinos en R.</li>
</ol>
<p>Ejemplo de referencia:</p>
<div class="sourceCode" id="cb356"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb356-1"><a href="anexos.html#cb356-1" tabindex="-1"></a>model2<span class="ot">&lt;-</span><span class="fu">nls</span>(bone<span class="sc">~</span>a<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span>c<span class="sc">*</span>age)), <span class="at">data =</span> deer,<span class="at">start=</span><span class="fu">list</span>(<span class="at">a=</span><span class="dv">120</span>,<span class="at">c=</span><span class="fl">0.064</span>))</span></code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><p>Realice el gráfico del modelo 1 (<code>model1</code>) junto con su gráfico de dispersión.</p></li>
<li><p>Deberán crear un segundo modelo a partir de los modelos estudiados en clase. Analice con detenimiento la forma de los datos y haga una selección apropiada.</p></li>
<li><p>Una vez escogido el modelo, haga una proceso de linealización y estime los parámetros a partir de un modelo de RLS.</p></li>
<li><p>Use los valores de las estimaciones de los coeficientes del modelo de RLS obtenidos en el punto anterior, como los valores iniciales para generar el modelo de RNLS a partir de la función <code>nls()</code>.</p></li>
<li><p>Genere el Modelo de RNLS y escriba la ecuación resultante. Además, realice el gráfico respectivo de este modelo junto con el gráfico de dispersión de los datos.</p></li>
<li><p>Utilice la función <code>anova</code> para comparar ambos modelos. ¿cuál modelos es el mejor?, gráficamente, ¿se puede llegar a esa misma conclusión?.</p></li>
</ol>
</div>
</div>
<div id="solucion-iii-parcial-de-estadistica" class="section level2 unnumbered hasAnchor">
<h2>Solucion III Parcial de Estadistica<a href="anexos.html#solucion-iii-parcial-de-estadistica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cargamos librerías:</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="anexos.html#cb357-1" tabindex="-1"></a><span class="fu">library</span>(bbmle)</span>
<span id="cb357-2"><a href="anexos.html#cb357-2" tabindex="-1"></a></span>
<span id="cb357-3"><a href="anexos.html#cb357-3" tabindex="-1"></a><span class="fu">library</span>(DALEX)</span></code></pre></div>
<pre><code>## Welcome to DALEX (version: 2.4.3).
## Find examples and detailed introduction at: http://ema.drwhy.ai/
## Additional features will be available after installation of: ggpubr.
## Use &#39;install_dependencies()&#39; to get all suggested dependencies</code></pre>
<pre><code>## 
## Attaching package: &#39;DALEX&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:dplyr&#39;:
## 
##     explain</code></pre>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="anexos.html#cb361-1" tabindex="-1"></a><span class="fu">library</span>(stats)</span></code></pre></div>
<p>Base de datos a trabajar:</p>
<div class="sourceCode" id="cb362"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb362-1"><a href="anexos.html#cb362-1" tabindex="-1"></a>tv <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">230.1</span>, <span class="fl">44.5</span>, <span class="fl">17.2</span>, <span class="fl">151.5</span>, <span class="fl">180.8</span>, <span class="fl">8.7</span>, <span class="fl">57.5</span>, <span class="fl">120.2</span>, <span class="fl">8.6</span>, <span class="fl">199.8</span>,</span>
<span id="cb362-2"><a href="anexos.html#cb362-2" tabindex="-1"></a><span class="fl">66.1</span>, <span class="fl">214.7</span>,</span>
<span id="cb362-3"><a href="anexos.html#cb362-3" tabindex="-1"></a> <span class="fl">23.8</span>, <span class="fl">97.5</span>, <span class="fl">204.1</span>, <span class="fl">195.4</span>, <span class="fl">67.8</span>, <span class="fl">281.4</span>, <span class="fl">69.2</span>, <span class="fl">147.3</span>, <span class="fl">218.4</span>, <span class="fl">237.4</span>,</span>
<span id="cb362-4"><a href="anexos.html#cb362-4" tabindex="-1"></a><span class="fl">13.2</span>, <span class="fl">228.3</span>,</span>
<span id="cb362-5"><a href="anexos.html#cb362-5" tabindex="-1"></a> <span class="fl">62.3</span>, <span class="fl">262.9</span>, <span class="fl">142.9</span>, <span class="fl">240.1</span>, <span class="fl">248.8</span>, <span class="fl">70.6</span>, <span class="fl">292.9</span>, <span class="fl">112.9</span>, <span class="fl">97.2</span>, <span class="fl">265.6</span>,</span>
<span id="cb362-6"><a href="anexos.html#cb362-6" tabindex="-1"></a><span class="fl">95.7</span>, <span class="fl">290.7</span>,</span>
<span id="cb362-7"><a href="anexos.html#cb362-7" tabindex="-1"></a> <span class="fl">266.9</span>, <span class="fl">74.7</span>, <span class="fl">43.1</span>, <span class="dv">228</span>, <span class="fl">202.5</span>, <span class="dv">177</span>, <span class="fl">293.6</span>, <span class="fl">206.9</span>, <span class="fl">25.1</span>, <span class="fl">175.1</span>, <span class="fl">89.7</span>,</span>
<span id="cb362-8"><a href="anexos.html#cb362-8" tabindex="-1"></a><span class="fl">239.9</span>, <span class="fl">227.2</span>,</span>
<span id="cb362-9"><a href="anexos.html#cb362-9" tabindex="-1"></a> <span class="fl">66.9</span>, <span class="fl">199.8</span>, <span class="fl">100.4</span>, <span class="fl">216.4</span>, <span class="fl">182.6</span>, <span class="fl">262.7</span>, <span class="fl">198.9</span>, <span class="fl">7.3</span>, <span class="fl">136.2</span>, <span class="fl">210.8</span>,</span>
<span id="cb362-10"><a href="anexos.html#cb362-10" tabindex="-1"></a><span class="fl">210.7</span>, <span class="fl">53.5</span>,</span>
<span id="cb362-11"><a href="anexos.html#cb362-11" tabindex="-1"></a> <span class="fl">261.3</span>, <span class="fl">239.3</span>, <span class="fl">102.7</span>, <span class="fl">131.1</span>, <span class="dv">69</span>, <span class="fl">31.5</span>, <span class="fl">139.3</span>, <span class="fl">237.4</span>, <span class="fl">216.8</span>, <span class="fl">199.1</span>,</span>
<span id="cb362-12"><a href="anexos.html#cb362-12" tabindex="-1"></a><span class="fl">109.8</span>, <span class="fl">26.8</span>,</span>
<span id="cb362-13"><a href="anexos.html#cb362-13" tabindex="-1"></a> <span class="fl">129.4</span>, <span class="fl">213.4</span>, <span class="fl">16.9</span>, <span class="fl">27.5</span>, <span class="fl">120.5</span>, <span class="fl">5.4</span>, <span class="dv">116</span>, <span class="fl">76.4</span>, <span class="fl">239.8</span>, <span class="fl">75.3</span>, <span class="fl">68.4</span>,</span>
<span id="cb362-14"><a href="anexos.html#cb362-14" tabindex="-1"></a><span class="fl">213.5</span>, <span class="fl">193.2</span>,</span>
<span id="cb362-15"><a href="anexos.html#cb362-15" tabindex="-1"></a> <span class="fl">76.3</span>, <span class="fl">110.7</span>, <span class="fl">88.3</span>, <span class="fl">109.8</span>, <span class="fl">134.3</span>, <span class="fl">28.6</span>, <span class="fl">217.7</span>, <span class="fl">250.9</span>, <span class="fl">107.4</span>, <span class="fl">163.3</span>,</span>
<span id="cb362-16"><a href="anexos.html#cb362-16" tabindex="-1"></a><span class="fl">197.6</span>, <span class="fl">184.9</span>,</span>
<span id="cb362-17"><a href="anexos.html#cb362-17" tabindex="-1"></a> <span class="fl">289.7</span>, <span class="fl">135.2</span>, <span class="fl">222.4</span>, <span class="fl">296.4</span>, <span class="fl">280.2</span>, <span class="fl">187.9</span>, <span class="fl">238.2</span>, <span class="fl">137.9</span>, <span class="dv">25</span>, <span class="fl">90.4</span>,</span>
<span id="cb362-18"><a href="anexos.html#cb362-18" tabindex="-1"></a><span class="fl">13.1</span>, <span class="fl">255.4</span>,</span>
<span id="cb362-19"><a href="anexos.html#cb362-19" tabindex="-1"></a> <span class="fl">225.8</span>, <span class="fl">241.7</span>, <span class="fl">175.7</span>, <span class="fl">209.6</span>, <span class="fl">78.2</span>, <span class="fl">75.1</span>, <span class="fl">139.2</span>, <span class="fl">76.4</span>, <span class="fl">125.7</span>, <span class="fl">19.4</span>,</span>
<span id="cb362-20"><a href="anexos.html#cb362-20" tabindex="-1"></a><span class="fl">141.3</span>, <span class="fl">18.8</span>,</span>
<span id="cb362-21"><a href="anexos.html#cb362-21" tabindex="-1"></a> <span class="dv">224</span>, <span class="fl">123.1</span>, <span class="fl">229.5</span>, <span class="fl">87.2</span>, <span class="fl">7.8</span>, <span class="fl">80.2</span>, <span class="fl">220.3</span>, <span class="fl">59.6</span>, <span class="fl">0.7</span>, <span class="fl">265.2</span>, <span class="fl">8.4</span>,</span>
<span id="cb362-22"><a href="anexos.html#cb362-22" tabindex="-1"></a><span class="fl">219.8</span>, <span class="fl">36.9</span>,</span>
<span id="cb362-23"><a href="anexos.html#cb362-23" tabindex="-1"></a> <span class="fl">48.3</span>, <span class="fl">25.6</span>, <span class="fl">273.7</span>, <span class="dv">43</span>, <span class="fl">184.9</span>, <span class="fl">73.4</span>, <span class="fl">193.7</span>, <span class="fl">220.5</span>, <span class="fl">104.6</span>, <span class="fl">96.2</span>, <span class="fl">140.3</span>,</span>
<span id="cb362-24"><a href="anexos.html#cb362-24" tabindex="-1"></a><span class="fl">240.1</span>,</span>
<span id="cb362-25"><a href="anexos.html#cb362-25" tabindex="-1"></a> <span class="fl">243.2</span>, <span class="dv">38</span>, <span class="fl">44.7</span>, <span class="fl">280.7</span>, <span class="dv">121</span>, <span class="fl">197.6</span>, <span class="fl">171.3</span>, <span class="fl">187.8</span>, <span class="fl">4.1</span>, <span class="fl">93.9</span>, <span class="fl">149.8</span>,</span>
<span id="cb362-26"><a href="anexos.html#cb362-26" tabindex="-1"></a><span class="fl">11.7</span>, <span class="fl">131.7</span>,</span>
<span id="cb362-27"><a href="anexos.html#cb362-27" tabindex="-1"></a> <span class="fl">172.5</span>, <span class="fl">85.7</span>, <span class="fl">188.4</span>, <span class="fl">163.5</span>, <span class="fl">117.2</span>, <span class="fl">234.5</span>, <span class="fl">17.9</span>, <span class="fl">206.8</span>, <span class="fl">215.4</span>, <span class="fl">284.3</span>,</span>
<span id="cb362-28"><a href="anexos.html#cb362-28" tabindex="-1"></a><span class="dv">50</span>, <span class="fl">164.5</span>,</span>
<span id="cb362-29"><a href="anexos.html#cb362-29" tabindex="-1"></a> <span class="fl">19.6</span>, <span class="fl">168.4</span>, <span class="fl">222.4</span>, <span class="fl">276.9</span>, <span class="fl">248.4</span>, <span class="fl">170.2</span>, <span class="fl">276.7</span>, <span class="fl">165.6</span>, <span class="fl">156.6</span>, <span class="fl">218.5</span>,</span>
<span id="cb362-30"><a href="anexos.html#cb362-30" tabindex="-1"></a><span class="fl">56.2</span>, <span class="fl">287.6</span>,</span>
<span id="cb362-31"><a href="anexos.html#cb362-31" tabindex="-1"></a> <span class="fl">253.8</span>, <span class="dv">205</span>, <span class="fl">139.5</span>, <span class="fl">191.1</span>, <span class="dv">286</span>, <span class="fl">18.7</span>, <span class="fl">39.5</span>, <span class="fl">75.5</span>, <span class="fl">17.2</span>, <span class="fl">166.8</span>, <span class="fl">149.7</span>,</span>
<span id="cb362-32"><a href="anexos.html#cb362-32" tabindex="-1"></a><span class="fl">38.2</span>, <span class="fl">94.2</span>,</span>
<span id="cb362-33"><a href="anexos.html#cb362-33" tabindex="-1"></a> <span class="dv">177</span>, <span class="fl">283.6</span>, <span class="fl">232.1</span>)</span>
<span id="cb362-34"><a href="anexos.html#cb362-34" tabindex="-1"></a>radio <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">37.8</span>, <span class="fl">39.3</span>, <span class="fl">45.9</span>, <span class="fl">41.3</span>, <span class="fl">10.8</span>, <span class="fl">48.9</span>, <span class="fl">32.8</span>, <span class="fl">19.6</span>, <span class="fl">2.1</span>, <span class="fl">2.6</span>, <span class="fl">5.8</span>,</span>
<span id="cb362-35"><a href="anexos.html#cb362-35" tabindex="-1"></a><span class="dv">24</span>, <span class="fl">35.1</span>,</span>
<span id="cb362-36"><a href="anexos.html#cb362-36" tabindex="-1"></a> <span class="fl">7.6</span>, <span class="fl">32.9</span>, <span class="fl">47.7</span>, <span class="fl">36.6</span>, <span class="fl">39.6</span>, <span class="fl">20.5</span>, <span class="fl">23.9</span>, <span class="fl">27.7</span>, <span class="fl">5.1</span>, <span class="fl">15.9</span>, <span class="fl">16.9</span>, <span class="fl">12.6</span>,</span>
<span id="cb362-37"><a href="anexos.html#cb362-37" tabindex="-1"></a><span class="fl">3.5</span>, <span class="fl">29.3</span>,</span>
<span id="cb362-38"><a href="anexos.html#cb362-38" tabindex="-1"></a> <span class="fl">16.7</span>, <span class="fl">27.1</span>, <span class="dv">16</span>, <span class="fl">28.3</span>, <span class="fl">17.4</span>, <span class="fl">1.5</span>, <span class="dv">20</span>, <span class="fl">1.4</span>, <span class="fl">4.1</span>, <span class="fl">43.8</span>, <span class="fl">49.4</span>, <span class="fl">26.7</span>,</span>
<span id="cb362-39"><a href="anexos.html#cb362-39" tabindex="-1"></a><span class="fl">37.7</span>, <span class="fl">22.3</span>,</span>
<span id="cb362-40"><a href="anexos.html#cb362-40" tabindex="-1"></a> <span class="fl">33.4</span>, <span class="fl">27.7</span>, <span class="fl">8.4</span>, <span class="fl">25.7</span>, <span class="fl">22.5</span>, <span class="fl">9.9</span>, <span class="fl">41.5</span>, <span class="fl">15.8</span>, <span class="fl">11.7</span>, <span class="fl">3.1</span>, <span class="fl">9.6</span>, <span class="fl">41.7</span>,</span>
<span id="cb362-41"><a href="anexos.html#cb362-41" tabindex="-1"></a><span class="fl">46.2</span>, <span class="fl">28.8</span>,</span>
<span id="cb362-42"><a href="anexos.html#cb362-42" tabindex="-1"></a> <span class="fl">49.4</span>, <span class="fl">28.1</span>, <span class="fl">19.2</span>, <span class="fl">49.6</span>, <span class="fl">29.5</span>, <span class="dv">2</span>, <span class="fl">42.7</span>, <span class="fl">15.5</span>, <span class="fl">29.6</span>, <span class="fl">42.8</span>, <span class="fl">9.3</span>, <span class="fl">24.6</span>,</span>
<span id="cb362-43"><a href="anexos.html#cb362-43" tabindex="-1"></a><span class="fl">14.5</span>, <span class="fl">27.5</span>,</span>
<span id="cb362-44"><a href="anexos.html#cb362-44" tabindex="-1"></a> <span class="fl">43.9</span>, <span class="fl">30.6</span>, <span class="fl">14.3</span>, <span class="dv">33</span>, <span class="fl">5.7</span>, <span class="fl">24.6</span>, <span class="fl">43.7</span>, <span class="fl">1.6</span>, <span class="fl">28.5</span>, <span class="fl">29.9</span>, <span class="fl">7.7</span>, <span class="fl">26.7</span>,</span>
<span id="cb362-45"><a href="anexos.html#cb362-45" tabindex="-1"></a><span class="fl">4.1</span>, <span class="fl">20.3</span>,</span>
<span id="cb362-46"><a href="anexos.html#cb362-46" tabindex="-1"></a> <span class="fl">44.5</span>, <span class="dv">43</span>, <span class="fl">18.4</span>, <span class="fl">27.5</span>, <span class="fl">40.6</span>, <span class="fl">25.5</span>, <span class="fl">47.8</span>, <span class="fl">4.9</span>, <span class="fl">1.5</span>, <span class="fl">33.5</span>, <span class="fl">36.5</span>, <span class="dv">14</span>,</span>
<span id="cb362-47"><a href="anexos.html#cb362-47" tabindex="-1"></a><span class="fl">31.6</span>, <span class="fl">3.5</span>,</span>
<span id="cb362-48"><a href="anexos.html#cb362-48" tabindex="-1"></a> <span class="dv">21</span>, <span class="fl">42.3</span>, <span class="fl">41.7</span>, <span class="fl">4.3</span>, <span class="fl">36.3</span>, <span class="fl">10.1</span>, <span class="fl">17.2</span>, <span class="fl">34.3</span>, <span class="fl">46.4</span>, <span class="dv">11</span>, <span class="fl">0.3</span>, <span class="fl">0.4</span>,</span>
<span id="cb362-49"><a href="anexos.html#cb362-49" tabindex="-1"></a><span class="fl">26.9</span>, <span class="fl">8.2</span>, <span class="dv">38</span>,</span>
<span id="cb362-50"><a href="anexos.html#cb362-50" tabindex="-1"></a> <span class="fl">15.4</span>, <span class="fl">20.6</span>, <span class="fl">46.8</span>, <span class="dv">35</span>, <span class="fl">14.3</span>, <span class="fl">0.8</span>, <span class="fl">36.9</span>, <span class="dv">16</span>, <span class="fl">26.8</span>, <span class="fl">21.7</span>, <span class="fl">2.4</span>, <span class="fl">34.6</span>,</span>
<span id="cb362-51"><a href="anexos.html#cb362-51" tabindex="-1"></a><span class="fl">32.3</span>, <span class="fl">11.8</span>,</span>
<span id="cb362-52"><a href="anexos.html#cb362-52" tabindex="-1"></a> <span class="fl">38.9</span>, <span class="dv">0</span>, <span class="dv">49</span>, <span class="dv">12</span>, <span class="fl">39.6</span>, <span class="fl">2.9</span>, <span class="fl">27.2</span>, <span class="fl">33.5</span>, <span class="fl">38.6</span>, <span class="dv">47</span>, <span class="dv">39</span>, <span class="fl">28.9</span>, <span class="fl">25.9</span>,</span>
<span id="cb362-53"><a href="anexos.html#cb362-53" tabindex="-1"></a><span class="fl">43.9</span>, <span class="dv">17</span>, <span class="fl">35.4</span>,</span>
<span id="cb362-54"><a href="anexos.html#cb362-54" tabindex="-1"></a> <span class="fl">33.2</span>, <span class="fl">5.7</span>, <span class="fl">14.8</span>, <span class="fl">1.9</span>, <span class="fl">7.3</span>, <span class="dv">49</span>, <span class="fl">40.3</span>, <span class="fl">25.8</span>, <span class="fl">13.9</span>, <span class="fl">8.4</span>, <span class="fl">23.3</span>, <span class="fl">39.7</span>,</span>
<span id="cb362-55"><a href="anexos.html#cb362-55" tabindex="-1"></a><span class="fl">21.1</span>, <span class="fl">11.6</span>,</span>
<span id="cb362-56"><a href="anexos.html#cb362-56" tabindex="-1"></a> <span class="fl">43.5</span>, <span class="fl">1.3</span>, <span class="fl">36.9</span>, <span class="fl">18.4</span>, <span class="fl">18.1</span>, <span class="fl">35.8</span>, <span class="fl">18.1</span>, <span class="fl">36.8</span>, <span class="fl">14.7</span>, <span class="fl">3.4</span>, <span class="fl">37.6</span>, <span class="fl">5.2</span>,</span>
<span id="cb362-57"><a href="anexos.html#cb362-57" tabindex="-1"></a><span class="fl">23.6</span>, <span class="fl">10.6</span>,</span>
<span id="cb362-58"><a href="anexos.html#cb362-58" tabindex="-1"></a> <span class="fl">11.6</span>, <span class="fl">20.9</span>, <span class="fl">20.1</span>, <span class="fl">7.1</span>, <span class="fl">3.4</span>, <span class="fl">48.9</span>, <span class="fl">30.2</span>, <span class="fl">7.8</span>, <span class="fl">2.3</span>, <span class="dv">10</span>, <span class="fl">2.6</span>, <span class="fl">5.4</span>, <span class="fl">5.7</span>,</span>
<span id="cb362-59"><a href="anexos.html#cb362-59" tabindex="-1"></a><span class="dv">43</span>, <span class="fl">21.3</span>,</span>
<span id="cb362-60"><a href="anexos.html#cb362-60" tabindex="-1"></a> <span class="fl">45.1</span>, <span class="fl">2.1</span>, <span class="fl">28.7</span>, <span class="fl">13.9</span>, <span class="fl">12.1</span>, <span class="fl">41.1</span>, <span class="fl">10.8</span>, <span class="fl">4.1</span>, <span class="dv">42</span>, <span class="fl">35.6</span>, <span class="fl">3.7</span>, <span class="fl">4.9</span>,</span>
<span id="cb362-61"><a href="anexos.html#cb362-61" tabindex="-1"></a><span class="fl">9.3</span>, <span class="dv">42</span>, <span class="fl">8.6</span>)</span>
<span id="cb362-62"><a href="anexos.html#cb362-62" tabindex="-1"></a>periodico <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">69.2</span>, <span class="fl">45.1</span>, <span class="fl">69.3</span>, <span class="fl">58.5</span>, <span class="fl">58.4</span>, <span class="dv">75</span>, <span class="fl">23.5</span>, <span class="fl">11.6</span>, <span class="dv">1</span>, <span class="fl">21.2</span>,</span>
<span id="cb362-63"><a href="anexos.html#cb362-63" tabindex="-1"></a><span class="fl">24.2</span>, <span class="dv">4</span>, <span class="fl">65.9</span>,</span>
<span id="cb362-64"><a href="anexos.html#cb362-64" tabindex="-1"></a> <span class="fl">7.2</span>, <span class="dv">46</span>, <span class="fl">52.9</span>, <span class="dv">114</span>, <span class="fl">55.8</span>, <span class="fl">18.3</span>, <span class="fl">19.1</span>, <span class="fl">53.4</span>, <span class="fl">23.5</span>, <span class="fl">49.6</span>, <span class="fl">26.2</span>, <span class="fl">18.3</span>,</span>
<span id="cb362-65"><a href="anexos.html#cb362-65" tabindex="-1"></a><span class="fl">19.5</span>, <span class="fl">12.6</span>,</span>
<span id="cb362-66"><a href="anexos.html#cb362-66" tabindex="-1"></a> <span class="fl">22.9</span>, <span class="fl">22.9</span>, <span class="fl">40.8</span>, <span class="fl">43.2</span>, <span class="fl">38.6</span>, <span class="dv">30</span>, <span class="fl">0.3</span>, <span class="fl">7.4</span>, <span class="fl">8.5</span>, <span class="dv">5</span>, <span class="fl">45.7</span>, <span class="fl">35.1</span>, <span class="dv">32</span>,</span>
<span id="cb362-67"><a href="anexos.html#cb362-67" tabindex="-1"></a><span class="fl">31.6</span>, <span class="fl">38.7</span>,</span>
<span id="cb362-68"><a href="anexos.html#cb362-68" tabindex="-1"></a> <span class="fl">1.8</span>, <span class="fl">26.4</span>, <span class="fl">43.3</span>, <span class="fl">31.5</span>, <span class="fl">35.7</span>, <span class="fl">18.5</span>, <span class="fl">49.9</span>, <span class="fl">36.8</span>, <span class="fl">34.6</span>, <span class="fl">3.6</span>, <span class="fl">39.6</span>, <span class="fl">58.7</span>,</span>
<span id="cb362-69"><a href="anexos.html#cb362-69" tabindex="-1"></a><span class="fl">15.9</span>, <span class="dv">60</span>,</span>
<span id="cb362-70"><a href="anexos.html#cb362-70" tabindex="-1"></a> <span class="fl">41.4</span>, <span class="fl">16.6</span>, <span class="fl">37.7</span>, <span class="fl">9.3</span>, <span class="fl">21.4</span>, <span class="fl">54.7</span>, <span class="fl">27.3</span>, <span class="fl">8.4</span>, <span class="fl">28.9</span>, <span class="fl">0.9</span>, <span class="fl">2.2</span>, <span class="fl">10.2</span>,</span>
<span id="cb362-71"><a href="anexos.html#cb362-71" tabindex="-1"></a><span class="dv">11</span>, <span class="fl">27.2</span>,</span>
<span id="cb362-72"><a href="anexos.html#cb362-72" tabindex="-1"></a> <span class="fl">38.7</span>, <span class="fl">31.7</span>, <span class="fl">19.3</span>, <span class="fl">31.3</span>, <span class="fl">13.1</span>, <span class="fl">89.4</span>, <span class="fl">20.7</span>, <span class="fl">14.2</span>, <span class="fl">9.4</span>, <span class="fl">23.1</span>, <span class="fl">22.3</span>,</span>
<span id="cb362-73"><a href="anexos.html#cb362-73" tabindex="-1"></a><span class="fl">36.9</span>, <span class="fl">32.5</span>,</span>
<span id="cb362-74"><a href="anexos.html#cb362-74" tabindex="-1"></a> <span class="fl">35.6</span>, <span class="fl">33.8</span>, <span class="fl">65.7</span>, <span class="dv">16</span>, <span class="fl">63.2</span>, <span class="fl">73.4</span>, <span class="fl">51.4</span>, <span class="fl">9.3</span>, <span class="dv">33</span>, <span class="dv">59</span>, <span class="fl">72.3</span>, <span class="fl">10.9</span>,</span>
<span id="cb362-75"><a href="anexos.html#cb362-75" tabindex="-1"></a><span class="fl">52.9</span>, <span class="fl">5.9</span>, <span class="dv">22</span>,</span>
<span id="cb362-76"><a href="anexos.html#cb362-76" tabindex="-1"></a> <span class="fl">51.2</span>, <span class="fl">45.9</span>, <span class="fl">49.8</span>, <span class="fl">100.9</span>, <span class="fl">21.4</span>, <span class="fl">17.9</span>, <span class="fl">5.3</span>, <span class="dv">59</span>, <span class="fl">29.7</span>, <span class="fl">23.2</span>, <span class="fl">25.6</span>, <span class="fl">5.5</span>,</span>
<span id="cb362-77"><a href="anexos.html#cb362-77" tabindex="-1"></a><span class="fl">56.5</span>, <span class="fl">23.2</span>,</span>
<span id="cb362-78"><a href="anexos.html#cb362-78" tabindex="-1"></a> <span class="fl">2.4</span>, <span class="fl">10.7</span>, <span class="fl">34.5</span>, <span class="fl">52.7</span>, <span class="fl">25.6</span>, <span class="fl">14.8</span>, <span class="fl">79.2</span>, <span class="fl">22.3</span>, <span class="fl">46.2</span>, <span class="fl">50.4</span>, <span class="fl">15.6</span>,</span>
<span id="cb362-79"><a href="anexos.html#cb362-79" tabindex="-1"></a><span class="fl">12.4</span>, <span class="fl">74.2</span>,</span>
<span id="cb362-80"><a href="anexos.html#cb362-80" tabindex="-1"></a> <span class="fl">25.9</span>, <span class="fl">50.6</span>, <span class="fl">9.2</span>, <span class="fl">3.2</span>, <span class="fl">43.1</span>, <span class="fl">8.7</span>, <span class="dv">43</span>, <span class="fl">2.1</span>, <span class="fl">45.1</span>, <span class="fl">65.6</span>, <span class="fl">8.5</span>, <span class="fl">9.3</span>, <span class="fl">59.7</span>,</span>
<span id="cb362-81"><a href="anexos.html#cb362-81" tabindex="-1"></a><span class="fl">20.5</span>, <span class="fl">1.7</span>,</span>
<span id="cb362-82"><a href="anexos.html#cb362-82" tabindex="-1"></a> <span class="fl">12.9</span>, <span class="fl">75.6</span>, <span class="fl">37.9</span>, <span class="fl">34.4</span>, <span class="fl">38.9</span>, <span class="dv">9</span>, <span class="fl">8.7</span>, <span class="fl">44.3</span>, <span class="fl">11.9</span>, <span class="fl">20.6</span>, <span class="dv">37</span>, <span class="fl">48.7</span>,</span>
<span id="cb362-83"><a href="anexos.html#cb362-83" tabindex="-1"></a><span class="fl">14.2</span>, <span class="fl">37.7</span>,</span>
<span id="cb362-84"><a href="anexos.html#cb362-84" tabindex="-1"></a> <span class="fl">9.5</span>, <span class="fl">5.7</span>, <span class="fl">50.5</span>, <span class="fl">24.3</span>, <span class="fl">45.2</span>, <span class="fl">34.6</span>, <span class="fl">30.7</span>, <span class="fl">49.3</span>, <span class="fl">25.6</span>, <span class="fl">7.4</span>, <span class="fl">5.4</span>, <span class="fl">84.8</span>,</span>
<span id="cb362-85"><a href="anexos.html#cb362-85" tabindex="-1"></a><span class="fl">21.6</span>, <span class="fl">19.4</span>,</span>
<span id="cb362-86"><a href="anexos.html#cb362-86" tabindex="-1"></a> <span class="fl">57.6</span>, <span class="fl">6.4</span>, <span class="fl">18.4</span>, <span class="fl">47.4</span>, <span class="dv">17</span>, <span class="fl">12.8</span>, <span class="fl">13.1</span>, <span class="fl">41.8</span>, <span class="fl">20.3</span>, <span class="fl">35.2</span>, <span class="fl">23.7</span>, <span class="fl">17.6</span>,</span>
<span id="cb362-87"><a href="anexos.html#cb362-87" tabindex="-1"></a><span class="fl">8.3</span>, <span class="fl">27.4</span>,</span>
<span id="cb362-88"><a href="anexos.html#cb362-88" tabindex="-1"></a> <span class="fl">29.7</span>, <span class="fl">71.8</span>, <span class="dv">30</span>, <span class="fl">19.6</span>, <span class="fl">26.6</span>, <span class="fl">18.2</span>, <span class="fl">3.7</span>, <span class="fl">23.4</span>, <span class="fl">5.8</span>, <span class="dv">6</span>, <span class="fl">31.6</span>, <span class="fl">3.6</span>, <span class="dv">6</span>,</span>
<span id="cb362-89"><a href="anexos.html#cb362-89" tabindex="-1"></a><span class="fl">13.8</span>, <span class="fl">8.1</span>,</span>
<span id="cb362-90"><a href="anexos.html#cb362-90" tabindex="-1"></a> <span class="fl">6.4</span>, <span class="fl">66.2</span>, <span class="fl">8.7</span>)</span>
<span id="cb362-91"><a href="anexos.html#cb362-91" tabindex="-1"></a>ventas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">22.1</span>, <span class="fl">10.4</span>, <span class="fl">9.3</span>, <span class="fl">18.5</span>, <span class="fl">12.9</span>, <span class="fl">7.2</span>, <span class="fl">11.8</span>, <span class="fl">13.2</span>, <span class="fl">4.8</span>, <span class="fl">10.6</span>, <span class="fl">8.6</span>,</span>
<span id="cb362-92"><a href="anexos.html#cb362-92" tabindex="-1"></a><span class="fl">17.4</span>, <span class="fl">9.2</span>,</span>
<span id="cb362-93"><a href="anexos.html#cb362-93" tabindex="-1"></a> <span class="fl">9.7</span>, <span class="dv">19</span>, <span class="fl">22.4</span>, <span class="fl">12.5</span>, <span class="fl">24.4</span>, <span class="fl">11.3</span>, <span class="fl">14.6</span>, <span class="dv">18</span>, <span class="fl">12.5</span>, <span class="fl">5.6</span>, <span class="fl">15.5</span>, <span class="fl">9.7</span>, <span class="dv">12</span>,</span>
<span id="cb362-94"><a href="anexos.html#cb362-94" tabindex="-1"></a><span class="dv">15</span>, <span class="fl">15.9</span>,</span>
<span id="cb362-95"><a href="anexos.html#cb362-95" tabindex="-1"></a> <span class="fl">18.9</span>, <span class="fl">10.5</span>, <span class="fl">21.4</span>, <span class="fl">11.9</span>, <span class="fl">9.6</span>, <span class="fl">17.4</span>, <span class="fl">9.5</span>, <span class="fl">12.8</span>, <span class="fl">25.4</span>, <span class="fl">14.7</span>, <span class="fl">10.1</span>, <span class="fl">21.5</span>,</span>
<span id="cb362-96"><a href="anexos.html#cb362-96" tabindex="-1"></a><span class="fl">16.6</span>, <span class="fl">17.1</span>,</span>
<span id="cb362-97"><a href="anexos.html#cb362-97" tabindex="-1"></a> <span class="fl">20.7</span>, <span class="fl">12.9</span>, <span class="fl">8.5</span>, <span class="fl">14.9</span>, <span class="fl">10.6</span>, <span class="fl">23.2</span>, <span class="fl">14.8</span>, <span class="fl">9.7</span>, <span class="fl">11.4</span>, <span class="fl">10.7</span>, <span class="fl">22.6</span>, <span class="fl">21.2</span>,</span>
<span id="cb362-98"><a href="anexos.html#cb362-98" tabindex="-1"></a><span class="fl">20.2</span>, <span class="fl">23.7</span>,</span>
<span id="cb362-99"><a href="anexos.html#cb362-99" tabindex="-1"></a> <span class="fl">5.5</span>, <span class="fl">13.2</span>, <span class="fl">23.8</span>, <span class="fl">18.4</span>, <span class="fl">8.1</span>, <span class="fl">24.2</span>, <span class="fl">15.7</span>, <span class="dv">14</span>, <span class="dv">18</span>, <span class="fl">9.3</span>, <span class="fl">9.5</span>, <span class="fl">13.4</span>, <span class="fl">18.9</span>,</span>
<span id="cb362-100"><a href="anexos.html#cb362-100" tabindex="-1"></a><span class="fl">22.3</span>, <span class="fl">18.3</span>,</span>
<span id="cb362-101"><a href="anexos.html#cb362-101" tabindex="-1"></a> <span class="fl">12.4</span>, <span class="fl">8.8</span>, <span class="dv">11</span>, <span class="dv">17</span>, <span class="fl">8.7</span>, <span class="fl">6.9</span>, <span class="fl">14.2</span>, <span class="fl">5.3</span>, <span class="dv">11</span>, <span class="fl">11.8</span>, <span class="fl">12.3</span>, <span class="fl">11.3</span>, <span class="fl">13.6</span>,</span>
<span id="cb362-102"><a href="anexos.html#cb362-102" tabindex="-1"></a><span class="fl">21.7</span>, <span class="fl">15.2</span>,</span>
<span id="cb362-103"><a href="anexos.html#cb362-103" tabindex="-1"></a> <span class="dv">12</span>, <span class="dv">16</span>, <span class="fl">12.9</span>, <span class="fl">16.7</span>, <span class="fl">11.2</span>, <span class="fl">7.3</span>, <span class="fl">19.4</span>, <span class="fl">22.2</span>, <span class="fl">11.5</span>, <span class="fl">16.9</span>, <span class="fl">11.7</span>, <span class="fl">15.5</span>,</span>
<span id="cb362-104"><a href="anexos.html#cb362-104" tabindex="-1"></a><span class="fl">25.4</span>, <span class="fl">17.2</span>,</span>
<span id="cb362-105"><a href="anexos.html#cb362-105" tabindex="-1"></a> <span class="fl">11.7</span>, <span class="fl">23.8</span>, <span class="fl">14.8</span>, <span class="fl">14.7</span>, <span class="fl">20.7</span>, <span class="fl">19.2</span>, <span class="fl">7.2</span>, <span class="fl">8.7</span>, <span class="fl">5.3</span>, <span class="fl">19.8</span>, <span class="fl">13.4</span>, <span class="fl">21.8</span>,</span>
<span id="cb362-106"><a href="anexos.html#cb362-106" tabindex="-1"></a><span class="fl">14.1</span>, <span class="fl">15.9</span>,</span>
<span id="cb362-107"><a href="anexos.html#cb362-107" tabindex="-1"></a> <span class="fl">14.6</span>, <span class="fl">12.6</span>, <span class="fl">12.2</span>, <span class="fl">9.4</span>, <span class="fl">15.9</span>, <span class="fl">6.6</span>, <span class="fl">15.5</span>, <span class="dv">7</span>, <span class="fl">11.6</span>, <span class="fl">15.2</span>, <span class="fl">19.7</span>, <span class="fl">10.6</span>,</span>
<span id="cb362-108"><a href="anexos.html#cb362-108" tabindex="-1"></a><span class="fl">6.6</span>, <span class="fl">8.8</span>,</span>
<span id="cb362-109"><a href="anexos.html#cb362-109" tabindex="-1"></a> <span class="fl">24.7</span>, <span class="fl">9.7</span>, <span class="fl">1.6</span>, <span class="fl">12.7</span>, <span class="fl">5.7</span>, <span class="fl">19.6</span>, <span class="fl">10.8</span>, <span class="fl">11.6</span>, <span class="fl">9.5</span>, <span class="fl">20.8</span>, <span class="fl">9.6</span>, <span class="fl">20.7</span>,</span>
<span id="cb362-110"><a href="anexos.html#cb362-110" tabindex="-1"></a><span class="fl">10.9</span>, <span class="fl">19.2</span>,</span>
<span id="cb362-111"><a href="anexos.html#cb362-111" tabindex="-1"></a> <span class="fl">20.1</span>, <span class="fl">10.4</span>, <span class="fl">11.4</span>, <span class="fl">10.3</span>, <span class="fl">13.2</span>, <span class="fl">25.4</span>, <span class="fl">10.9</span>, <span class="fl">10.1</span>, <span class="fl">16.1</span>, <span class="fl">11.6</span>, <span class="fl">16.6</span>, <span class="dv">19</span>,</span>
<span id="cb362-112"><a href="anexos.html#cb362-112" tabindex="-1"></a><span class="fl">15.6</span>, <span class="fl">3.2</span>,</span>
<span id="cb362-113"><a href="anexos.html#cb362-113" tabindex="-1"></a> <span class="fl">15.3</span>, <span class="fl">10.1</span>, <span class="fl">7.3</span>, <span class="fl">12.9</span>, <span class="fl">14.4</span>, <span class="fl">13.3</span>, <span class="fl">14.9</span>, <span class="dv">18</span>, <span class="fl">11.9</span>, <span class="fl">11.9</span>, <span class="dv">8</span>, <span class="fl">12.2</span>,</span>
<span id="cb362-114"><a href="anexos.html#cb362-114" tabindex="-1"></a><span class="fl">17.1</span>, <span class="dv">15</span>, <span class="fl">8.4</span>,</span>
<span id="cb362-115"><a href="anexos.html#cb362-115" tabindex="-1"></a> <span class="fl">14.5</span>, <span class="fl">7.6</span>, <span class="fl">11.7</span>, <span class="fl">11.5</span>, <span class="dv">27</span>, <span class="fl">20.2</span>, <span class="fl">11.7</span>, <span class="fl">11.8</span>, <span class="fl">12.6</span>, <span class="fl">10.5</span>, <span class="fl">12.2</span>, <span class="fl">8.7</span>,</span>
<span id="cb362-116"><a href="anexos.html#cb362-116" tabindex="-1"></a><span class="fl">26.2</span>, <span class="fl">17.6</span>,</span>
<span id="cb362-117"><a href="anexos.html#cb362-117" tabindex="-1"></a> <span class="fl">22.6</span>, <span class="fl">10.3</span>, <span class="fl">17.3</span>, <span class="fl">15.9</span>, <span class="fl">6.7</span>, <span class="fl">10.8</span>, <span class="fl">9.9</span>, <span class="fl">5.9</span>, <span class="fl">19.6</span>, <span class="fl">17.3</span>, <span class="fl">7.6</span>, <span class="fl">9.7</span>,</span>
<span id="cb362-118"><a href="anexos.html#cb362-118" tabindex="-1"></a><span class="fl">12.8</span>, <span class="fl">25.5</span>,</span>
<span id="cb362-119"><a href="anexos.html#cb362-119" tabindex="-1"></a> <span class="fl">13.4</span>)</span>
<span id="cb362-120"><a href="anexos.html#cb362-120" tabindex="-1"></a></span>
<span id="cb362-121"><a href="anexos.html#cb362-121" tabindex="-1"></a>datos.ventas <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(tv, radio, periodico, ventas)</span></code></pre></div>
<p>Exportamos la base de datos, para facilitársela a los estudiantes:</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="anexos.html#cb363-1" tabindex="-1"></a><span class="co">#write.csv(datos.ventas, file=&quot;DatosVentas.csv&quot;)</span></span></code></pre></div>
<p>La idea es generar 3 modelos y excoger el que mejor explica los datos</p>
<div id="modelo-0-regresión-lineal-simple" class="section level3 unnumbered hasAnchor">
<h3>Modelo 0: Regresión lineal simple<a href="anexos.html#modelo-0-regresión-lineal-simple" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="anexos.html#cb364-1" tabindex="-1"></a>mod0 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ventas <span class="sc">~</span> tv , <span class="at">data =</span> datos.ventas)</span>
<span id="cb364-2"><a href="anexos.html#cb364-2" tabindex="-1"></a><span class="fu">summary</span>(mod0)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv, data = datos.ventas)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.3860 -1.9545 -0.1913  2.0671  7.2124 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 7.032594   0.457843   15.36   &lt;2e-16 ***
## tv          0.047537   0.002691   17.67   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.259 on 198 degrees of freedom
## Multiple R-squared:  0.6119, Adjusted R-squared:  0.6099 
## F-statistic: 312.1 on 1 and 198 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Ecuación del modelo 0</strong>:<span class="math inline">\(\text{ventas} = 7.032594 + + 0.047537 \cdot \text{tv}\)</span></p>
</div>
<div id="modelo-1-regresion-lineal-multiple-con-todas-las-variables" class="section level3 unnumbered hasAnchor">
<h3>Modelo 1: Regresion lineal multiple con todas las variables<a href="anexos.html#modelo-1-regresion-lineal-multiple-con-todas-las-variables" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Seguidamente se crea una modelo de regresión Lineal Múltiple que toma en consideración a todas las variables.</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="anexos.html#cb366-1" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ventas <span class="sc">~</span> tv <span class="sc">+</span> radio <span class="sc">+</span> periodico, <span class="at">data =</span> datos.ventas)</span>
<span id="cb366-2"><a href="anexos.html#cb366-2" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv + radio + periodico, data = datos.ventas)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.8277 -0.8908  0.2418  1.1893  2.8292 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.938889   0.311908   9.422   &lt;2e-16 ***
## tv           0.045765   0.001395  32.809   &lt;2e-16 ***
## radio        0.188530   0.008611  21.893   &lt;2e-16 ***
## periodico   -0.001037   0.005871  -0.177     0.86    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.686 on 196 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8956 
## F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Ecuación del modelo 1:</strong> <span class="math inline">\(\text{ventas} = 2.9389 + 0.0448 \text{tv} + 0.1885 \text{radio} - 0.001 \text{periodico}\)</span></p>
<p>Se identifica por el <code>p-value</code> que el coeficiente parcial de variable periodico no contribuye de forma significativa al modelo, por lo que se concluye que las variables tv y radio están relacionadas con la cantidad de ventas.</p>
</div>
<div id="modelo-2-regresion-lineal-multiple-con-variables-tv-y-radio" class="section level3 unnumbered hasAnchor">
<h3>Modelo 2: Regresion Lineal Multiple con Variables TV y Radio<a href="anexos.html#modelo-2-regresion-lineal-multiple-con-variables-tv-y-radio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Seguidamente se crea el segundo modelo:</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="anexos.html#cb368-1" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ventas <span class="sc">~</span> tv <span class="sc">+</span> radio , <span class="at">data =</span> datos.ventas)</span>
<span id="cb368-2"><a href="anexos.html#cb368-2" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv + radio, data = datos.ventas)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -8.7977 -0.8752  0.2422  1.1708  2.8328 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.92110    0.29449   9.919   &lt;2e-16 ***
## tv           0.04575    0.00139  32.909   &lt;2e-16 ***
## radio        0.18799    0.00804  23.382   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.681 on 197 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8962 
## F-statistic: 859.6 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Ecuación del modelo 2:</strong> <span class="math inline">\(\text{ventas} = = 2.9211 + 0.04575 \text{tv} + 0.18799 \text{radio}\)</span></p>
<p>Note que el <span class="math inline">\(R^2\)</span> mejoró de manera importante</p>
</div>
<div id="modelo-3-regresion-no-lineal-multiple-con-interacción" class="section level3 hasAnchor" number="13.2.1">
<h3><span class="header-section-number">13.2.1</span> Modelo 3: Regresion no Lineal Multiple (Con Interacción)<a href="anexos.html#modelo-3-regresion-no-lineal-multiple-con-interacción" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>El siguiente modelo agrega al modelo de regresión lineal múltiple, un componente de interacción entre las variables.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="anexos.html#cb370-1" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ventas <span class="sc">~</span> tv <span class="sc">+</span> radio <span class="sc">+</span> tv<span class="sc">*</span>radio , <span class="at">data =</span> datos.ventas)</span>
<span id="cb370-2"><a href="anexos.html#cb370-2" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv + radio + tv * radio, data = datos.ventas)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.3366 -0.4028  0.1831  0.5948  1.5246 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6.750e+00  2.479e-01  27.233   &lt;2e-16 ***
## tv          1.910e-02  1.504e-03  12.699   &lt;2e-16 ***
## radio       2.886e-02  8.905e-03   3.241   0.0014 ** 
## tv:radio    1.086e-03  5.242e-05  20.727   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9435 on 196 degrees of freedom
## Multiple R-squared:  0.9678, Adjusted R-squared:  0.9673 
## F-statistic:  1963 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Otra forma de hacerlo, es generando una nueva columna a la tabla:</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="anexos.html#cb372-1" tabindex="-1"></a>vector <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb372-2"><a href="anexos.html#cb372-2" tabindex="-1"></a>vector[<span class="fu">seq</span>(<span class="dv">1</span>,<span class="dv">200</span>,<span class="dv">1</span>)] <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="fu">c</span>(<span class="dv">1</span>))</span>
<span id="cb372-3"><a href="anexos.html#cb372-3" tabindex="-1"></a>datos.ventas2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(vector, datos.ventas[ ,<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>)], datos.ventas[</span>
<span id="cb372-4"><a href="anexos.html#cb372-4" tabindex="-1"></a>,<span class="dv">1</span>]<span class="sc">*</span>datos.ventas[ ,<span class="dv">2</span>], datos.ventas<span class="sc">$</span>ventas )</span>
<span id="cb372-5"><a href="anexos.html#cb372-5" tabindex="-1"></a><span class="fu">names</span>(datos.ventas2)</span></code></pre></div>
<pre><code>## [1] &quot;vector&quot;                               
## [2] &quot;tv&quot;                                   
## [3] &quot;radio&quot;                                
## [4] &quot;datos.ventas[, 1] * datos.ventas[, 2]&quot;
## [5] &quot;datos.ventas$ventas&quot;</code></pre>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="anexos.html#cb374-1" tabindex="-1"></a><span class="do">## [1] &quot;vector&quot;</span></span>
<span id="cb374-2"><a href="anexos.html#cb374-2" tabindex="-1"></a><span class="do">## [2] &quot;tv&quot;</span></span>
<span id="cb374-3"><a href="anexos.html#cb374-3" tabindex="-1"></a><span class="do">## [3] &quot;radio&quot;</span></span>
<span id="cb374-4"><a href="anexos.html#cb374-4" tabindex="-1"></a><span class="do">## [4] &quot;datos.ventas[, 1] * datos.ventas[, 2]&quot;</span></span>
<span id="cb374-5"><a href="anexos.html#cb374-5" tabindex="-1"></a><span class="do">## [5] &quot;datos.ventas$ventas&quot;</span></span>
<span id="cb374-6"><a href="anexos.html#cb374-6" tabindex="-1"></a><span class="fu">names</span> (datos.ventas2)[<span class="dv">1</span>] <span class="ot">=</span> <span class="st">&quot;Unos&quot;</span></span>
<span id="cb374-7"><a href="anexos.html#cb374-7" tabindex="-1"></a><span class="fu">names</span> (datos.ventas2)[<span class="dv">4</span>] <span class="ot">=</span> <span class="st">&quot;tvradio&quot;</span></span>
<span id="cb374-8"><a href="anexos.html#cb374-8" tabindex="-1"></a><span class="fu">names</span> (datos.ventas2)[<span class="dv">5</span>] <span class="ot">=</span> <span class="st">&quot;ventas&quot;</span></span>
<span id="cb374-9"><a href="anexos.html#cb374-9" tabindex="-1"></a><span class="fu">names</span>(datos.ventas2)</span></code></pre></div>
<pre><code>## [1] &quot;Unos&quot;    &quot;tv&quot;      &quot;radio&quot;   &quot;tvradio&quot; &quot;ventas&quot;</code></pre>
<p>Seguidamente se genera el modelo inclouyendo la interacción:</p>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="anexos.html#cb376-1" tabindex="-1"></a>mod3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ventas <span class="sc">~</span> tv <span class="sc">+</span> radio <span class="sc">+</span> tvradio , <span class="at">data =</span> datos.ventas2)</span>
<span id="cb376-2"><a href="anexos.html#cb376-2" tabindex="-1"></a><span class="fu">summary</span>(mod3)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ventas ~ tv + radio + tvradio, data = datos.ventas2)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.3366 -0.4028  0.1831  0.5948  1.5246 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 6.750e+00  2.479e-01  27.233   &lt;2e-16 ***
## tv          1.910e-02  1.504e-03  12.699   &lt;2e-16 ***
## radio       2.886e-02  8.905e-03   3.241   0.0014 ** 
## tvradio     1.086e-03  5.242e-05  20.727   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9435 on 196 degrees of freedom
## Multiple R-squared:  0.9678, Adjusted R-squared:  0.9673 
## F-statistic:  1963 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Ecuación del modelo 3</strong>: <span class="math inline">\(\text{ventas} = = 6.75 + 0.0191 \text{tv} + 0.0289 \text{radio} + 0.0011 \text{tvradio}\)</span></p>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="anexos.html#cb378-1" tabindex="-1"></a><span class="co"># Modelo 1</span></span>
<span id="cb378-2"><a href="anexos.html#cb378-2" tabindex="-1"></a><span class="fu">summary</span>(mod0)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.6118751</code></pre>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="anexos.html#cb380-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">summary</span>(mod0)<span class="sc">$</span>r.squared)</span></code></pre></div>
<pre><code>## [1] 0.7822244</code></pre>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="anexos.html#cb382-1" tabindex="-1"></a><span class="co"># Modelo 1</span></span>
<span id="cb382-2"><a href="anexos.html#cb382-2" tabindex="-1"></a><span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.8972106</code></pre>
<div class="sourceCode" id="cb384"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb384-1"><a href="anexos.html#cb384-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">summary</span>(mod1)<span class="sc">$</span>r.squared)</span></code></pre></div>
<pre><code>## [1] 0.947212</code></pre>
<div class="sourceCode" id="cb386"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb386-1"><a href="anexos.html#cb386-1" tabindex="-1"></a><span class="co"># Modelo 2</span></span>
<span id="cb386-2"><a href="anexos.html#cb386-2" tabindex="-1"></a><span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.8971943</code></pre>
<div class="sourceCode" id="cb388"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb388-1"><a href="anexos.html#cb388-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">summary</span>(mod2)<span class="sc">$</span>r.squared)</span></code></pre></div>
<pre><code>## [1] 0.9472034</code></pre>
<div class="sourceCode" id="cb390"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb390-1"><a href="anexos.html#cb390-1" tabindex="-1"></a><span class="co"># Modelo 3</span></span>
<span id="cb390-2"><a href="anexos.html#cb390-2" tabindex="-1"></a><span class="fu">summary</span>(mod3)<span class="sc">$</span>r.squared</span></code></pre></div>
<pre><code>## [1] 0.9677905</code></pre>
<div class="sourceCode" id="cb392"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb392-1"><a href="anexos.html#cb392-1" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">summary</span>(mod3)<span class="sc">$</span>r.squared)</span></code></pre></div>
<pre><code>## [1] 0.9837635</code></pre>
<p>El estudiante debe dar una interpretación.</p>
<p>El mejor modelo según <span class="math inline">\(R^2\)</span> y <span class="math inline">\(R\)</span> es el Modelo 3, sin embargo no discrimina entre los modelos 1 y 2, pero el modelo 0 parece ser el peor de todos.</p>
<p>Seguidamente, hacemos una comparación entre ambos modelos usando sus residuos.</p>
<p>Use el comando: <code>AICctab(mod0, mod1, mod2, mod3, base = T, delta = T, sort= T, weights = T, nobs = 200)</code></p>
<div class="sourceCode" id="cb394"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb394-1"><a href="anexos.html#cb394-1" tabindex="-1"></a><span class="co"># Paquete bbmle</span></span>
<span id="cb394-2"><a href="anexos.html#cb394-2" tabindex="-1"></a><span class="fu">AICctab</span>(mod0, mod1, mod2, mod3, <span class="at">base =</span> T, <span class="at">delta =</span> T, <span class="at">sort =</span> T, <span class="at">weights =</span> T, <span class="at">nobs =</span> <span class="dv">200</span>)</span></code></pre></div>
<pre><code>##      AICc   dAICc  df weight
## mod3  550.6    0.0 5  1     
## mod2  780.6  230.0 4  &lt;0.001
## mod1  782.7  232.1 5  &lt;0.001
## mod0 1044.2  493.6 3  &lt;0.001</code></pre>
<p>Note que sigue siendo el modelo 3 el mejor, seguido por el modelo 2.</p>
<p>Tercera comparación</p>
<div class="sourceCode" id="cb396"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb396-1"><a href="anexos.html#cb396-1" tabindex="-1"></a><span class="co">#paquete DALEX</span></span>
<span id="cb396-2"><a href="anexos.html#cb396-2" tabindex="-1"></a><span class="co">#exp_lm1 &lt;- explain(mod1, data = datos.ventas, label = &quot;lm&quot;, y =datos.ventas$ventas)</span></span>
<span id="cb396-3"><a href="anexos.html#cb396-3" tabindex="-1"></a>exp_lm0 <span class="ot">&lt;-</span> <span class="fu">explain</span>(mod0, <span class="at">data =</span> datos.ventas, <span class="at">label =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">y =</span></span>
<span id="cb396-4"><a href="anexos.html#cb396-4" tabindex="-1"></a>datos.ventas<span class="sc">$</span>ventas)</span></code></pre></div>
<pre><code>## Preparation of a new explainer is initiated
##   -&gt; model label       :  lm 
##   -&gt; data              :  200  rows  4  cols 
##   -&gt; target variable   :  200  values 
##   -&gt; predict function  :  yhat.lm  will be used (  default  )
##   -&gt; predicted values  :  No value for predict function target column. (  default  )
##   -&gt; model_info        :  package stats , ver. 4.4.1 , task regression (  default  ) 
##   -&gt; predicted values  :  numerical, min =  7.065869 , mean =  14.0225 , max =  21.12245  
##   -&gt; residual function :  difference between y and yhat (  default  )
##   -&gt; residuals         :  numerical, min =  -8.385982 , mean =  -3.250733e-15 , max =  7.212369  
##   A new explainer has been created!</code></pre>
<div class="sourceCode" id="cb398"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb398-1"><a href="anexos.html#cb398-1" tabindex="-1"></a>exp_lm2 <span class="ot">&lt;-</span> <span class="fu">explain</span>(mod2, <span class="at">data =</span> datos.ventas, <span class="at">label =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">y =</span></span>
<span id="cb398-2"><a href="anexos.html#cb398-2" tabindex="-1"></a>datos.ventas<span class="sc">$</span>ventas)</span></code></pre></div>
<pre><code>## Preparation of a new explainer is initiated
##   -&gt; model label       :  lm 
##   -&gt; data              :  200  rows  4  cols 
##   -&gt; target variable   :  200  values 
##   -&gt; predict function  :  yhat.lm  will be used (  default  )
##   -&gt; predicted values  :  No value for predict function target column. (  default  )
##   -&gt; model_info        :  package stats , ver. 4.4.1 , task regression (  default  ) 
##   -&gt; predicted values  :  numerical, min =  3.595686 , mean =  14.0225 , max =  24.78353  
##   -&gt; residual function :  difference between y and yhat (  default  )
##   -&gt; residuals         :  numerical, min =  -8.7977 , mean =  -6.834533e-15 , max =  2.832837  
##   A new explainer has been created!</code></pre>
<div class="sourceCode" id="cb400"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb400-1"><a href="anexos.html#cb400-1" tabindex="-1"></a>exp_lm3 <span class="ot">&lt;-</span> <span class="fu">explain</span>(mod3, <span class="at">data =</span> datos.ventas2, <span class="at">label =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">y =</span></span>
<span id="cb400-2"><a href="anexos.html#cb400-2" tabindex="-1"></a>datos.ventas2<span class="sc">$</span>ventas)</span></code></pre></div>
<pre><code>## Preparation of a new explainer is initiated
##   -&gt; model label       :  lm 
##   -&gt; data              :  200  rows  5  cols 
##   -&gt; target variable   :  200  values 
##   -&gt; predict function  :  yhat.lm  will be used (  default  )
##   -&gt; predicted values  :  No value for predict function target column. (  default  )
##   -&gt; model_info        :  package stats , ver. 4.4.1 , task regression (  default  ) 
##   -&gt; predicted values  :  numerical, min =  6.994718 , mean =  14.0225 , max =  28.16216  
##   -&gt; residual function :  difference between y and yhat (  default  )
##   -&gt; residuals         :  numerical, min =  -6.336578 , mean =  -4.494044e-15 , max =  1.52462  
##   A new explainer has been created!</code></pre>
<div class="sourceCode" id="cb402"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb402-1"><a href="anexos.html#cb402-1" tabindex="-1"></a><span class="fu">class</span>(mod1)</span></code></pre></div>
<pre><code>## [1] &quot;lm&quot;</code></pre>
<p>Se crea un Model Performance para cada modelo, a partir de los Model Explainer ya creados:</p>
<div class="sourceCode" id="cb404"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb404-1"><a href="anexos.html#cb404-1" tabindex="-1"></a>mp_lm0 <span class="ot">&lt;-</span> <span class="fu">model_performance</span>(exp_lm0)</span>
<span id="cb404-2"><a href="anexos.html#cb404-2" tabindex="-1"></a>mp_lm1 <span class="ot">&lt;-</span> <span class="fu">model_performance</span>(exp_lm2)</span>
<span id="cb404-3"><a href="anexos.html#cb404-3" tabindex="-1"></a>mp_lm2 <span class="ot">&lt;-</span> <span class="fu">model_performance</span>(exp_lm3)</span></code></pre></div>
<p>Finalmente, se grafican los modelos de desempeño:</p>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="anexos.html#cb405-1" tabindex="-1"></a><span class="fu">plot</span>( mp_lm1, mp_lm2, mp_lm0)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-113-1.png" width="672" /></p>
<p>Finalmente, se realiza la prueba de anova</p>
<div class="sourceCode" id="cb406"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb406-1"><a href="anexos.html#cb406-1" tabindex="-1"></a>stats<span class="sc">::</span><span class="fu">anova</span>(mod0, mod1, mod2, mod3, <span class="at">test=</span><span class="st">&quot;F&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: ventas ~ tv
## Model 2: ventas ~ tv + radio + periodico
## Model 3: ventas ~ tv + radio
## Model 4: ventas ~ tv + radio + tvradio
##   Res.Df     RSS Df Sum of Sq        F Pr(&gt;F)    
## 1    198 2102.53                                 
## 2    196  556.83  2   1545.71 272.0407 &lt;2e-16 ***
## 3    197  556.91 -1     -0.09   0.0312 0.8599    
## 4    196  174.48  1    382.43 134.6139 &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="referencias.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
