<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 12 Regresion no lineal simple | “Elementos de Estadística Inferencial con R”</title>
  <meta name="description" content="Capítulo 12 Regresion no lineal simple | “Elementos de Estadística Inferencial con R”" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 12 Regresion no lineal simple | “Elementos de Estadística Inferencial con R”" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 12 Regresion no lineal simple | “Elementos de Estadística Inferencial con R”" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regresion-y-correlacion-lineal.html"/>
<link rel="next" href="regresion-lineal-multiple.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="" data-path="introduccion.html"><a href="introduccion.html"><i class="fa fa-check"></i>Introduccion</a></li>
<li class="chapter" data-level="1" data-path="cargar-chunks.html"><a href="cargar-chunks.html"><i class="fa fa-check"></i><b>1</b> Cargar Chunks</a></li>
<li class="chapter" data-level="2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html"><i class="fa fa-check"></i><b>2</b> I Parte: Casos para una poblacion</a>
<ul>
<li class="chapter" data-level="2.1" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#simulacion-de-intervalos-de-confianza"><i class="fa fa-check"></i><b>2.1</b> Simulacion de Intervalos de Confianza</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#método-de-simulacion-ejemplo-1"><i class="fa fa-check"></i><b>2.1.1</b> Método de simulacion: Ejemplo 1</a></li>
<li class="chapter" data-level="2.1.2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#método-de-simulación-ejemplo-2"><i class="fa fa-check"></i><b>2.1.2</b> Método de simulación: Ejemplo 2</a></li>
<li class="chapter" data-level="2.1.3" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#experimento-con-la-confianza"><i class="fa fa-check"></i><b>2.1.3</b> Experimento con la “Confianza”</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#intervalos-de-confianza-para-el-parameto-p"><i class="fa fa-check"></i><b>2.2</b> Intervalos de confianza para el parameto p</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#método-exacto-o-de-clopper-pearson"><i class="fa fa-check"></i><b>2.2.1</b> Método “exacto” o de Clopper-Pearson</a></li>
<li class="chapter" data-level="2.2.2" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#metodo-de-wilson"><i class="fa fa-check"></i><b>2.2.2</b> Metodo de Wilson</a></li>
<li class="chapter" data-level="2.2.3" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#metodo-de-laplace"><i class="fa fa-check"></i><b>2.2.3</b> Metodo de Laplace</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="i-parte-casos-para-una-poblacion.html"><a href="i-parte-casos-para-una-poblacion.html#intervalo-de-confianza-para-la-varianza-de-una-poblacion-normal"><i class="fa fa-check"></i><b>2.3</b> Intervalo de confianza para la varianza de una poblacion normal</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html"><i class="fa fa-check"></i><b>3</b> II Parte: Casos con dos poblaciones</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html#diferencia-de-promedios"><i class="fa fa-check"></i><b>3.1</b> Diferencia de Promedios</a></li>
<li class="chapter" data-level="3.2" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html#cociente-de-varianzas"><i class="fa fa-check"></i><b>3.2</b> Cociente de varianzas</a></li>
<li class="chapter" data-level="3.3" data-path="ii-parte-casos-con-dos-poblaciones.html"><a href="ii-parte-casos-con-dos-poblaciones.html#diferencia-de-proporciones"><i class="fa fa-check"></i><b>3.3</b> Diferencia de proporciones</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html"><i class="fa fa-check"></i><b>4</b> Pruebas de hipotesis para una poblacion</a>
<ul>
<li class="chapter" data-level="4.1" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#prueba-de-hipotesis-para-micro"><i class="fa fa-check"></i><b>4.1</b> Prueba de hipotesis para Micro</a></li>
<li class="chapter" data-level="4.2" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#prueba-de-hipotesis-para-p"><i class="fa fa-check"></i><b>4.2</b> Prueba de hipotesis para p</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#muestas-pequeñas"><i class="fa fa-check"></i><b>4.2.1</b> Muestas Pequeñas</a></li>
<li class="chapter" data-level="4.2.2" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#muestas-grandes"><i class="fa fa-check"></i><b>4.2.2</b> Muestas Grandes</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="pruebas-de-hipotesis-para-una-poblacion.html"><a href="pruebas-de-hipotesis-para-una-poblacion.html#prueba-de-hipotesis-para-sigma-de-una-variable-aleatoria-con-comportamiento-normal"><i class="fa fa-check"></i><b>4.3</b> Prueba de hipotesis para sigma de una variable aleatoria con comportamiento normal</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html"><i class="fa fa-check"></i><b>5</b> Pruebas de hipotesis para dos poblaciones</a>
<ul>
<li class="chapter" data-level="5.1" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#introducción"><i class="fa fa-check"></i><b>5.1</b> Introducción</a></li>
<li class="chapter" data-level="5.2" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#casos-de-dos-poblaciones"><i class="fa fa-check"></i><b>5.2</b> Casos de Dos poblaciones</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#prueba-de-hipotesis-para-dos-medias-poblacionales-mu_1-y-mu_2"><i class="fa fa-check"></i><b>5.2.1</b> Prueba de hipotesis para dos medias poblacionales <span class="math inline">\(\mu_1\)</span> y <span class="math inline">\(\mu_2\)</span></a></li>
<li class="chapter" data-level="5.2.2" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#contraste-para-dos-medias-independientes-en-r-funcion-t.test"><i class="fa fa-check"></i><b>5.2.2</b> Contraste para dos medias independientes en R: funcion t.test</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#prueba-de-hipotesis-para-dos-proporciones-p_1-p_2"><i class="fa fa-check"></i><b>5.3</b> Prueba de hipotesis para dos proporciones <span class="math inline">\(p_1, p_2\)</span></a></li>
<li class="chapter" data-level="5.4" data-path="pruebas-de-hipotesis-para-dos-poblaciones.html"><a href="pruebas-de-hipotesis-para-dos-poblaciones.html#prueba-de-hipotesis-para-dos-varianzas-de-sigma_12-sigma_22"><i class="fa fa-check"></i><b>5.4</b> Prueba de hipotesis para dos varianzas de <span class="math inline">\(\sigma_1^2\)</span>, <span class="math inline">\(\sigma_2^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="una-visión-grafica-de-las-pruebas-de-hipotesis.html"><a href="una-visión-grafica-de-las-pruebas-de-hipotesis.html"><i class="fa fa-check"></i><b>6</b> Una visión grafica de las pruebas de hipotesis</a></li>
<li class="chapter" data-level="7" data-path="otras-pruebas-de-hipotesis.html"><a href="otras-pruebas-de-hipotesis.html"><i class="fa fa-check"></i><b>7</b> Otras pruebas de Hipotesis</a></li>
<li class="chapter" data-level="8" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html"><i class="fa fa-check"></i><b>8</b> Prueba de Bondad de Ajuste</a>
<ul>
<li class="chapter" data-level="8.1" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#visualización-de-datos"><i class="fa fa-check"></i><b>8.1</b> Visualización de datos</a></li>
<li class="chapter" data-level="8.2" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#pruebas-formales-de-normalidad"><i class="fa fa-check"></i><b>8.2</b> Pruebas formales de normalidad</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-de-kolmogorov-smirnov-lilliefors-o-k-s-l-test"><i class="fa fa-check"></i><b>8.2.1</b> Test de Kolmogorov-Smirnov-Lilliefors o K-S-L test</a></li>
<li class="chapter" data-level="8.2.2" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-de-normalidad-de-anderson-darling-o-a-d-test"><i class="fa fa-check"></i><b>8.2.2</b> Test de normalidad de Anderson-Darling o A-D test</a></li>
<li class="chapter" data-level="8.2.3" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-de-shapiro-wilks-o-s-w-test"><i class="fa fa-check"></i><b>8.2.3</b> Test de Shapiro-Wilks o S-W test</a></li>
<li class="chapter" data-level="8.2.4" data-path="prueba-de-bondad-de-ajuste.html"><a href="prueba-de-bondad-de-ajuste.html#test-omnibus-de-dagostino-pearson"><i class="fa fa-check"></i><b>8.2.4</b> Test omnibus de D’Agostino-Pearson</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="prueba-de-independencia.html"><a href="prueba-de-independencia.html"><i class="fa fa-check"></i><b>9</b> Prueba de Independencia</a></li>
<li class="chapter" data-level="10" data-path="prueba-de-analisis-de-varianza-anova.html"><a href="prueba-de-analisis-de-varianza-anova.html"><i class="fa fa-check"></i><b>10</b> Prueba de Analisis de Varianza (ANOVA)</a></li>
<li class="chapter" data-level="11" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html"><i class="fa fa-check"></i><b>11</b> Regresion y correlacion lineal</a>
<ul>
<li class="chapter" data-level="11.1" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#generando-el-modelo-de-regresion"><i class="fa fa-check"></i><b>11.1</b> Generando el modelo de regresion</a></li>
<li class="chapter" data-level="11.2" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#coeficientes-de-determinación-y-correlacion"><i class="fa fa-check"></i><b>11.2</b> Coeficientes de determinación y correlacion</a></li>
<li class="chapter" data-level="11.3" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#prueba-para-los-residuos"><i class="fa fa-check"></i><b>11.3</b> Prueba para los residuos</a></li>
<li class="chapter" data-level="11.4" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#intervalos-de-confianza-para-la-pendiente-y-el-intercepto"><i class="fa fa-check"></i><b>11.4</b> Intervalos de confianza para la pendiente y el intercepto</a></li>
<li class="chapter" data-level="11.5" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#intervalo-de-confianza-y-prediccion"><i class="fa fa-check"></i><b>11.5</b> Intervalo de confianza y prediccion</a></li>
<li class="chapter" data-level="11.6" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#constraste-de-hipotesis"><i class="fa fa-check"></i><b>11.6</b> Constraste de hipotesis</a></li>
<li class="chapter" data-level="11.7" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#comprobacion-de-las-variabilidades-presentes"><i class="fa fa-check"></i><b>11.7</b> Comprobacion de las variabilidades presentes</a></li>
<li class="chapter" data-level="11.8" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#cuidado-con-el-coeficiente-de-correlacion-y-de-determinación"><i class="fa fa-check"></i><b>11.8</b> Cuidado con el coeficiente de correlacion y de determinación</a></li>
<li class="chapter" data-level="11.9" data-path="regresion-y-correlacion-lineal.html"><a href="regresion-y-correlacion-lineal.html#ejemplo-2-correlaciones"><i class="fa fa-check"></i><b>11.9</b> EJEMPLO 2: CORRELACIONES</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="regresion-no-lineal-simple.html"><a href="regresion-no-lineal-simple.html"><i class="fa fa-check"></i><b>12</b> Regresion no lineal simple</a></li>
<li class="chapter" data-level="13" data-path="regresion-lineal-multiple.html"><a href="regresion-lineal-multiple.html"><i class="fa fa-check"></i><b>13</b> Regresion lineal multiple</a>
<ul>
<li class="chapter" data-level="13.1" data-path="regresion-lineal-multiple.html"><a href="regresion-lineal-multiple.html#regresion-lineal-multiple-rlm"><i class="fa fa-check"></i><b>13.1</b> Regresion Lineal Multiple (RLM)</a></li>
<li class="chapter" data-level="13.2" data-path="regresion-lineal-multiple.html"><a href="regresion-lineal-multiple.html#regresión-no-lineal-multiple-rnlm"><i class="fa fa-check"></i><b>13.2</b> Regresión No Lineal Multiple (RNLM)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html"><i class="fa fa-check"></i>Anexos</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#especificaciones-del-proyecto"><i class="fa fa-check"></i>Especificaciones del proyecto</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#i-parte-explicacion-de-los-datos"><i class="fa fa-check"></i>I Parte: Explicacion de los datos</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#ii-parte-analisis-inferencial-ic"><i class="fa fa-check"></i>II Parte: Analisis Inferencial (IC)</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones"><i class="fa fa-check"></i>III Parte: Analisis Inferencial (pruebas de hipotesis de una y dos poblaciones)</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iv-parte-analisis-inferencial-otras-pruebas-de-hipótesis"><i class="fa fa-check"></i>IV Parte: Analisis Inferencial (Otras pruebas de hipótesis)</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#v-parte-analisis-de-regresión"><i class="fa fa-check"></i>V Parte: : Analisis de regresión</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#fases-del-proyecto-y-detalles-de-entrega"><i class="fa fa-check"></i>Fases del proyecto y detalles de entrega</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#especificaciones-del-proyecto-ii-fase"><i class="fa fa-check"></i>Especificaciones del proyecto II Fase</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iii-parte-analisis-inferencial-pruebas-de-hipotesis-de-una-y-dos-poblaciones-1"><i class="fa fa-check"></i>III parte: Analisis Inferencial (pruebas de hipotesis de una y dos poblaciones)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#espesificaciones-del-proyecto-fase-iii"><i class="fa fa-check"></i>Espesificaciones del proyecto Fase III</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#i-parte-otras-pruebas-de-hipotesis-en-r"><i class="fa fa-check"></i>I Parte: Otras pruebas de hipotesis en R</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-1"><i class="fa fa-check"></i>Caso 1</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-2"><i class="fa fa-check"></i>Caso 2</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-3"><i class="fa fa-check"></i>Caso 3</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-4"><i class="fa fa-check"></i>Caso 4</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#ii-parte-modelos-de-regresion-lineal"><i class="fa fa-check"></i>II Parte: Modelos de regresion lineal</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-5"><i class="fa fa-check"></i>Caso 5</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-6"><i class="fa fa-check"></i>Caso 6</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#generacion-de-los-modelos"><i class="fa fa-check"></i>Generacion de los modelos</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#seleccionando-el-mejor-modelo"><i class="fa fa-check"></i>Seleccionando el mejor modelo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#iii-parte-modelos-de-regresion-no-lineal"><i class="fa fa-check"></i>III PARTE: Modelos de regresion no lineal</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#caso-7"><i class="fa fa-check"></i>Caso 7</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#solucion-iii-parcial-de-estadistica"><i class="fa fa-check"></i>Solucion III Parcial de Estadistica</a>
<ul>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#modelo-0-regresión-lineal-simple"><i class="fa fa-check"></i>Modelo 0: Regresión lineal simple</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#modelo-1-regresion-lineal-multiple-con-todas-las-variables"><i class="fa fa-check"></i>Modelo 1: Regresion lineal multiple con todas las variables</a></li>
<li class="chapter" data-level="" data-path="anexos.html"><a href="anexos.html#modelo-2-regresion-lineal-multiple-con-variables-tv-y-radio"><i class="fa fa-check"></i>Modelo 2: Regresion Lineal Multiple con Variables TV y Radio</a></li>
<li class="chapter" data-level="13.2.1" data-path="anexos.html"><a href="anexos.html#modelo-3-regresion-no-lineal-multiple-con-interacción"><i class="fa fa-check"></i><b>13.2.1</b> Modelo 3: Regresion no Lineal Multiple (Con Interacción)</a></li>
</ul></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">“Elementos de Estadística Inferencial con R”</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regresion-no-lineal-simple" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Capítulo 12</span> Regresion no lineal simple<a href="regresion-no-lineal-simple.html#regresion-no-lineal-simple" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En este material se trabajarán algunos ejemplos que ilustran la forma en que se puede
proceder a la modelación de datos mediante el <strong>Regresión No Lineal Simple</strong>.</p>
<p>En adelante, se usará las siguientes abreviaturas:</p>
<ul>
<li><p>Modelo de Regresión Lineal Simple: <strong>MRLS</strong></p></li>
<li><p>Modelo de Regresión No Lineal Simple: <strong>MRNLS</strong></p></li>
</ul>
<p>Seguidamente, los paquetes que vamos a utilizar:</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="regresion-no-lineal-simple.html#cb217-1" tabindex="-1"></a><span class="co">#library(stats)</span></span>
<span id="cb217-2"><a href="regresion-no-lineal-simple.html#cb217-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb217-3"><a href="regresion-no-lineal-simple.html#cb217-3" tabindex="-1"></a><span class="co">#library(nortest)</span></span></code></pre></div>
<p><strong>Ejemplo 1</strong>:</p>
<p>Considere los datos de la siguiente tabla:</p>
<table>
<thead>
<tr class="header">
<th align="center">X</th>
<th align="center">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">18</td>
<td align="center">19</td>
</tr>
<tr class="even">
<td align="center">19</td>
<td align="center">40</td>
</tr>
<tr class="odd">
<td align="center">19.5</td>
<td align="center">79</td>
</tr>
<tr class="even">
<td align="center">19.7</td>
<td align="center">130</td>
</tr>
<tr class="odd">
<td align="center">19.9</td>
<td align="center">397</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Escoja y justifique un modelo de regresión para 𝑌 como función de 𝑋, sabiendo que la variable 𝑋 por su naturaleza, toma valores menores que 20.</p></li>
<li><p>Determine el valor esperado de <span class="math inline">\(Y\)</span> cuando <span class="math inline">\(x = 17\)</span></p></li>
<li><p>Determine un Intervalo de Confianza para los parámetros <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>, según el modelo escogido previamente.</p></li>
</ul>
<p>Para escoger el modelo, se recomienda primeramente construir un gráfico de dispersión para ver la tendencia de los datos:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="regresion-no-lineal-simple.html#cb218-1" tabindex="-1"></a><span class="co"># Creamos la tabla de valores</span></span>
<span id="cb218-2"><a href="regresion-no-lineal-simple.html#cb218-2" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">19</span>, <span class="fl">19.5</span>, <span class="fl">19.7</span>, <span class="fl">19.9</span>) </span>
<span id="cb218-3"><a href="regresion-no-lineal-simple.html#cb218-3" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">40</span>, <span class="dv">79</span>, <span class="dv">130</span>, <span class="dv">397</span>)</span>
<span id="cb218-4"><a href="regresion-no-lineal-simple.html#cb218-4" tabindex="-1"></a></span>
<span id="cb218-5"><a href="regresion-no-lineal-simple.html#cb218-5" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y) <span class="co"># se juntan las columnas</span></span>
<span id="cb218-6"><a href="regresion-no-lineal-simple.html#cb218-6" tabindex="-1"></a>datos.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datos) <span class="co"># se crea un objeto dataframe</span></span>
<span id="cb218-7"><a href="regresion-no-lineal-simple.html#cb218-7" tabindex="-1"></a><span class="fu">names</span>(datos.df) <span class="co"># verificamos los nombres de las columnas</span></span></code></pre></div>
<pre><code>## [1] &quot;X&quot; &quot;Y&quot;</code></pre>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="regresion-no-lineal-simple.html#cb220-1" tabindex="-1"></a><span class="co"># Se crea un gráfico de dipsersión para ver de manera exporatoria los datos</span></span>
<span id="cb220-2"><a href="regresion-no-lineal-simple.html#cb220-2" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos.df, <span class="fu">aes</span>(X, Y))</span>
<span id="cb220-3"><a href="regresion-no-lineal-simple.html#cb220-3" tabindex="-1"></a>g1 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">stroke =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## Warning in geom_point(shape = 21, width = 0.3, alpha = 0.4, fill = &quot;blue&quot;, :
## Ignoring unknown parameters: `width`</code></pre>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-58-1.png" width="672" /></p>
<p>De los datos anteriores, se considera que un buen modelo de RNLS para los datos, puede ser el <strong>Modelo Hiperbólico</strong>, es decir:</p>
<table>
<colgroup>
<col width="30%" />
<col width="70%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">Modelo</th>
<th align="center">Transformación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(y = \frac{x}{\alpha x + \beta}\)</span></td>
<td align="center">Aplicando logaritmo natural: <br> <span class="math inline">\(\frac{1}{y} = a + \beta \cdot \frac{1}{x}\)</span></td>
</tr>
<tr class="even">
<td align="center">Condiciones</td>
<td align="center">Cambios de variable: <br> <span class="math inline">\(y_1 = \frac{1}{y}; \; x_1 = \frac{1}{x}; \; \beta_0 = \alpha; \; \beta_1 = \beta\)</span></td>
</tr>
<tr class="odd">
<td align="center">Posee asíntotas verticales y horizontales que no necesariamente son los ejes</td>
<td align="center">Modelo lineal obtenido: <br> <span class="math inline">\(y_1 = \beta_0 + \beta_1 \cdot x_1\)</span></td>
</tr>
</tbody>
</table>
<p><em>Foto</em></p>
<p>Lo anterior debido a que se percibe del gráfico que conforme <span class="math inline">\(x \rightarrow 20^-\)</span>, los valores de <span class="math inline">\(y\)</span> crecen rápidamente, semejando en <span class="math inline">\(x = 20\)</span> una asíntota vertical. Otros modelos como el exponencial se descarta por no tener asíntotas verticales y el potencial o recíproco solo tienen asíntota vertical en <span class="math inline">\(x = 0\)</span></p>
<p>Procedemos con las modificaciones en la tabla de datos, para transformar el modelo en un caso lineal, es decir, se hace una linealización de los datos:</p>
<p>Según la transformación recomendada, se debe hacer dos cambios de variable: <span class="math inline">\(X_2 = \frac{1}{X}\)</span> y <span class="math inline">\(Y_2 = \frac{1}{Y}\)</span>, para luego suministrarle estos valores a la función <code>lm</code> de R para crear una MRL:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="regresion-no-lineal-simple.html#cb222-1" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>X</span>
<span id="cb222-2"><a href="regresion-no-lineal-simple.html#cb222-2" tabindex="-1"></a>Y2 <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>Y</span>
<span id="cb222-3"><a href="regresion-no-lineal-simple.html#cb222-3" tabindex="-1"></a></span>
<span id="cb222-4"><a href="regresion-no-lineal-simple.html#cb222-4" tabindex="-1"></a>datos2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X2, Y2)</span>
<span id="cb222-5"><a href="regresion-no-lineal-simple.html#cb222-5" tabindex="-1"></a>datos2.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datos2)</span>
<span id="cb222-6"><a href="regresion-no-lineal-simple.html#cb222-6" tabindex="-1"></a>modelolm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y2 <span class="sc">~</span> X2, <span class="at">data =</span> datos2.df)</span>
<span id="cb222-7"><a href="regresion-no-lineal-simple.html#cb222-7" tabindex="-1"></a>modelolm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y2 ~ X2, data = datos2.df)
## 
## Coefficients:
## (Intercept)           X2  
##     -0.4698       9.4032</code></pre>
<p>Del modelo anterior se tiene que:</p>
<p><span class="math inline">\(a = -0.4698\)</span> y <span class="math inline">\(\beta = 9.4032\)</span></p>
<p>Por lo que haciendo nuevamente la transformación, el modelo buscado sería:</p>
<p><span class="math display">\[
y = \frac{x}{-0.4698x + 9.4032}
\]</span>
Los siguiente códigos ayudarán a mostrar gráficamente el modelo obtenido con respecto a los datos del gráfico de dispersión:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="regresion-no-lineal-simple.html#cb224-1" tabindex="-1"></a><span class="co"># Se genera una secuencia de puntos, para simular continuidad en la gráfica</span></span>
<span id="cb224-2"><a href="regresion-no-lineal-simple.html#cb224-2" tabindex="-1"></a>xo <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(X) <span class="sc">-</span> <span class="fl">0.2</span>, <span class="at">to =</span> <span class="fu">max</span>(X) <span class="sc">+</span> <span class="fl">0.2</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb224-3"><a href="regresion-no-lineal-simple.html#cb224-3" tabindex="-1"></a>yo <span class="ot">&lt;-</span> xo<span class="sc">/</span>(<span class="sc">-</span><span class="fl">0.4698</span><span class="sc">*</span>xo <span class="sc">+</span> <span class="fl">9.4032</span>)</span>
<span id="cb224-4"><a href="regresion-no-lineal-simple.html#cb224-4" tabindex="-1"></a><span class="co"># Graficamos dispersión y el modelo de ajuste en un mismo plot</span></span>
<span id="cb224-5"><a href="regresion-no-lineal-simple.html#cb224-5" tabindex="-1"></a><span class="fu">plot</span>(X,Y, <span class="at">main =</span> <span class="st">&quot;Modelo de RNLS f(x)=-x/(0.4698*x + 9.4032)&quot;</span>, <span class="at">col =</span><span class="st">&quot;darkblue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb224-6"><a href="regresion-no-lineal-simple.html#cb224-6" tabindex="-1"></a><span class="fu">lines</span>(xo, yo, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-60-1.png" width="672" /></p>
<p>Otra opción para el gráfico es usar ggplot2, como se muestra en el siguente código:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="regresion-no-lineal-simple.html#cb225-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y, xo, yo) <span class="co"># se juntan las columnas</span></span></code></pre></div>
<pre><code>## Warning in cbind(X, Y, xo, yo): number of rows of result is not a multiple of
## vector length (arg 1)</code></pre>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="regresion-no-lineal-simple.html#cb227-1" tabindex="-1"></a>data.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data) <span class="co"># se crea un objeto dataframe</span></span>
<span id="cb227-2"><a href="regresion-no-lineal-simple.html#cb227-2" tabindex="-1"></a><span class="fu">names</span>(data.df) <span class="co"># verificamos los nombres de las columnas</span></span></code></pre></div>
<pre><code>## [1] &quot;X&quot;  &quot;Y&quot;  &quot;xo&quot; &quot;yo&quot;</code></pre>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="regresion-no-lineal-simple.html#cb229-1" tabindex="-1"></a><span class="co"># Se crea un gráfico de dipsersión para ver de manera exploratoria los datos y se sobrepone el modelo de RNLS que encontramos f(x)=-x/(0.4698*x + 9.4032. Note que dentro de las opciones, para dar un mejor acabado al gráfico, se limita el intervalo de &quot;x&quot; e &quot;y&quot;</span></span>
<span id="cb229-2"><a href="regresion-no-lineal-simple.html#cb229-2" tabindex="-1"></a></span>
<span id="cb229-3"><a href="regresion-no-lineal-simple.html#cb229-3" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data.df, <span class="fu">aes</span>(X, Y, <span class="at">xmin =</span> <span class="fl">17.7</span>, <span class="at">xmax =</span> <span class="fl">20.3</span>, <span class="at">ymin =</span> <span class="sc">-</span><span class="dv">100</span>, <span class="at">ymax =</span> <span class="dv">500</span> ))</span>
<span id="cb229-4"><a href="regresion-no-lineal-simple.html#cb229-4" tabindex="-1"></a>g3 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">stroke =</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> xo, <span class="at">y =</span> yo), <span class="at">colour =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb229-5"><a href="regresion-no-lineal-simple.html#cb229-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;Modelo RNLS&quot;</span>)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-61-1.png" width="672" /></p>
<p>Tome en cuenta que los vectores <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son más pequeños que los vectores <span class="math inline">\(Xo\)</span> e <span class="math inline">\(Yo\)</span> que fueron creados solamente con fines estéticos de la graficación, entonces, R se encarga de equilibrar en dimensión los vectores generando secuencias repedidas de los vectores <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> hasta completar las filas, pero, sin alterar los pares ordenados originales.</p>
<p>Seguidamente a manera de ilustración, se muestran las tablas:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="regresion-no-lineal-simple.html#cb230-1" tabindex="-1"></a><span class="fu">head</span>(datos.df)</span></code></pre></div>
<pre><code>##      X   Y
## 1 18.0  19
## 2 19.0  40
## 3 19.5  79
## 4 19.7 130
## 5 19.9 397</code></pre>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="regresion-no-lineal-simple.html#cb232-1" tabindex="-1"></a><span class="fu">head</span>(data.df, <span class="dv">15</span>)</span></code></pre></div>
<pre><code>##       X   Y    xo       yo
## 1  18.0  19 17.80 17.10289
## 2  19.0  40 17.81 17.19009
## 3  19.5  79 17.82 17.27809
## 4  19.7 130 17.83 17.36689
## 5  19.9 397 17.84 17.45652
## 6  18.0  19 17.85 17.54696
## 7  19.0  40 17.86 17.63825
## 8  19.5  79 17.87 17.73039
## 9  19.7 130 17.88 17.82339
## 10 19.9 397 17.89 17.91727
## 11 18.0  19 17.90 18.01203
## 12 19.0  40 17.91 18.10770
## 13 19.5  79 17.92 18.20428
## 14 19.7 130 17.93 18.30178
## 15 19.9 397 17.94 18.40023</code></pre>
<p>Seguidamente se determina el IC para los parámetros <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>:</p>
<div class="sourceCode" id="cb234"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb234-1"><a href="regresion-no-lineal-simple.html#cb234-1" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">lm</span>(Y2 <span class="sc">~</span> X2, <span class="at">data =</span> datos2.df),<span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) -0.4781531 -0.461396
## X2           9.2425203  9.563962</code></pre>
<p>Finalmente, evaluamos el modelo en <span class="math inline">\(x = 17\)</span></p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="regresion-no-lineal-simple.html#cb236-1" tabindex="-1"></a>modelohiper1 <span class="ot">&lt;-</span> <span class="cf">function</span>(x){</span>
<span id="cb236-2"><a href="regresion-no-lineal-simple.html#cb236-2" tabindex="-1"></a> y <span class="ot">&lt;-</span> x<span class="sc">/</span>(<span class="sc">-</span><span class="fl">0.4698</span><span class="sc">*</span>x <span class="sc">+</span> <span class="fl">9.4032</span>)</span>
<span id="cb236-3"><a href="regresion-no-lineal-simple.html#cb236-3" tabindex="-1"></a> <span class="fu">return</span>(y)</span>
<span id="cb236-4"><a href="regresion-no-lineal-simple.html#cb236-4" tabindex="-1"></a>}</span>
<span id="cb236-5"><a href="regresion-no-lineal-simple.html#cb236-5" tabindex="-1"></a><span class="fu">modelohiper1</span>(<span class="dv">17</span>)</span></code></pre></div>
<pre><code>## [1] 12.00056</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="regresion-no-lineal-simple.html#cb238-1" tabindex="-1"></a>valores <span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">17</span>, <span class="fl">18.1</span>, <span class="fl">18.5</span>, <span class="fl">18.9</span>, <span class="fl">19.65</span>)</span>
<span id="cb238-2"><a href="regresion-no-lineal-simple.html#cb238-2" tabindex="-1"></a><span class="fu">modelohiper1</span>(valores)</span></code></pre></div>
<pre><code>## [1]  12.00056  20.11513  25.98680  36.07008 114.49047</code></pre>
<div class="sourceCode" id="cb240"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb240-1"><a href="regresion-no-lineal-simple.html#cb240-1" tabindex="-1"></a>datosnlm <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y) </span>
<span id="cb240-2"><a href="regresion-no-lineal-simple.html#cb240-2" tabindex="-1"></a>datosnlm.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datosnlm)</span>
<span id="cb240-3"><a href="regresion-no-lineal-simple.html#cb240-3" tabindex="-1"></a>datosnlm.df</span></code></pre></div>
<pre><code>##      X   Y
## 1 18.0  19
## 2 19.0  40
## 3 19.5  79
## 4 19.7 130
## 5 19.9 397</code></pre>
<div class="sourceCode" id="cb242"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb242-1"><a href="regresion-no-lineal-simple.html#cb242-1" tabindex="-1"></a>modelohiper2 <span class="ot">&lt;-</span> <span class="fu">nls</span>(Y <span class="sc">~</span> X<span class="sc">/</span>(a<span class="sc">*</span>X<span class="sc">+</span>b), <span class="at">data =</span> datosnlm.df, <span class="at">start =</span> <span class="fu">list</span>(<span class="at">a =</span><span class="dv">1</span>, <span class="at">b =</span> <span class="dv">1</span>))</span>
<span id="cb242-2"><a href="regresion-no-lineal-simple.html#cb242-2" tabindex="-1"></a>modelohiper2</span></code></pre></div>
<pre><code>## Nonlinear regression model
##   model: Y ~ X/(a * X + b)
##    data: datosnlm.df
##       a       b 
## -0.4983  9.9655 
##  residual sum-of-squares: 7.458
## 
## Number of iterations to convergence: 11 
## Achieved convergence tolerance: 7.917e-06</code></pre>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="regresion-no-lineal-simple.html#cb244-1" tabindex="-1"></a>xo <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(X) <span class="sc">-</span> <span class="fl">0.2</span>, <span class="at">to =</span> <span class="fu">max</span>(X) <span class="sc">+</span> <span class="fl">0.2</span>, <span class="at">by =</span> <span class="fl">0.01</span>)</span>
<span id="cb244-2"><a href="regresion-no-lineal-simple.html#cb244-2" tabindex="-1"></a>yo <span class="ot">&lt;-</span> xo<span class="sc">/</span>(<span class="sc">-</span><span class="fl">0.4983</span><span class="sc">*</span>xo <span class="sc">+</span> <span class="fl">9.9655</span>)</span>
<span id="cb244-3"><a href="regresion-no-lineal-simple.html#cb244-3" tabindex="-1"></a></span>
<span id="cb244-4"><a href="regresion-no-lineal-simple.html#cb244-4" tabindex="-1"></a>datanlm <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y, xo, yo)</span></code></pre></div>
<pre><code>## Warning in cbind(X, Y, xo, yo): number of rows of result is not a multiple of
## vector length (arg 1)</code></pre>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="regresion-no-lineal-simple.html#cb246-1" tabindex="-1"></a>datanlm.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datanlm)</span>
<span id="cb246-2"><a href="regresion-no-lineal-simple.html#cb246-2" tabindex="-1"></a></span>
<span id="cb246-3"><a href="regresion-no-lineal-simple.html#cb246-3" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datanlm.df, <span class="fu">aes</span>(X, Y, <span class="at">xmin =</span> <span class="fl">17.7</span>, <span class="at">xmax =</span> <span class="fl">20.01</span>, <span class="at">ymin =</span> <span class="sc">-</span><span class="dv">100</span>, <span class="at">ymax =</span> <span class="dv">500</span> ))</span>
<span id="cb246-4"><a href="regresion-no-lineal-simple.html#cb246-4" tabindex="-1"></a></span>
<span id="cb246-5"><a href="regresion-no-lineal-simple.html#cb246-5" tabindex="-1"></a>g3 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">stroke =</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> xo, <span class="at">y =</span> yo), <span class="at">colour =</span> <span class="st">&quot;darkblue&quot;</span>)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-64-1.png" width="672" /></p>
<p><strong>Ejemplo 2</strong>:</p>
<p>Considere los datos de la siguiente tabla:</p>
<table>
<thead>
<tr class="header">
<th align="center">x</th>
<th align="center">Y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">4</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">7</td>
</tr>
<tr class="odd">
<td align="center">4</td>
<td align="center">20</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">40</td>
</tr>
</tbody>
</table>
<p>A partir de los datos, estime el coeficiente <span class="math inline">\(\beta\)</span> de la ecuación de regresión <span class="math inline">\(y = 3 + x^\beta\)</span>, transformando el modelo a un modelo a un modelo de Regresión Lineal Simple mediante el método de mínimos cuadrados.</p>
<p>Para escoger el modelo, se recomienda primeramente construir un gráfico de dispersión para ver la tendencia de los datos:</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="regresion-no-lineal-simple.html#cb247-1" tabindex="-1"></a><span class="co"># Creamos la tabla de valores</span></span>
<span id="cb247-2"><a href="regresion-no-lineal-simple.html#cb247-2" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>) </span>
<span id="cb247-3"><a href="regresion-no-lineal-simple.html#cb247-3" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">20</span>, <span class="dv">40</span>) </span>
<span id="cb247-4"><a href="regresion-no-lineal-simple.html#cb247-4" tabindex="-1"></a>datos3 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y) <span class="co"># se juntan las columnas</span></span>
<span id="cb247-5"><a href="regresion-no-lineal-simple.html#cb247-5" tabindex="-1"></a>datos3.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datos3) <span class="co"># se crea un objeto dataframe</span></span>
<span id="cb247-6"><a href="regresion-no-lineal-simple.html#cb247-6" tabindex="-1"></a><span class="fu">names</span>(datos3.df) <span class="co"># verificamos los nombres de las columnas</span></span></code></pre></div>
<pre><code>## [1] &quot;X&quot; &quot;Y&quot;</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="regresion-no-lineal-simple.html#cb249-1" tabindex="-1"></a><span class="co"># Se crea un gráfico de dipsersión para ver de manera exporatoria los datos</span></span>
<span id="cb249-2"><a href="regresion-no-lineal-simple.html#cb249-2" tabindex="-1"></a>g1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datos3.df, <span class="fu">aes</span>(X, Y))</span>
<span id="cb249-3"><a href="regresion-no-lineal-simple.html#cb249-3" tabindex="-1"></a>g1 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">fill =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">stroke =</span> <span class="dv">1</span>)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p>De los datos anteriores, se considera que un buen modelo de regresión No lineal para los datos, puede ser el <strong>Modelo Potencial</strong>, es decir:
| Modelo | Transformación |
| <span class="math inline">\(y = a \cdot x^\beta\)</span> | Aplicando logaritmo natural: <br> <span class="math inline">\(ln(y) = ln(\alpha) + \beta \cdot ln(x)\)</span> |
| Condiciones: | Cambios de variable: <br> $ y_1 = ln(y); ; x_1 = ln(x); ; _0 = ln(); ; _1 = $ |
| Si <span class="math inline">\(\beta &gt; 0\)</span>, el modelo pasa por <span class="math inline">\((0,0)\)</span> | Modelo lineal obtenido: <br> <span class="math inline">\(y_1 = \beta_0 + \beta_1 \cdot x_1\)</span> |</p>
<p><em>Foto</em></p>
<p>Note que el modelo propuesto, discrepa del modelo base en una constante, pero esto no limita a que se pueda linealizar, sin embargo, no de puede adoptar las recomendaciones de la imagen tal cuál se detallan, sino que podemos hacer la transformación como sigue.</p>
<p><span class="math display">\[
y = 3 + x^\beta \\
y-3 = x^\beta \\
ln(y-3) = ln(x^\beta) \\
ln(y-3) = \beta \; ln(x) \\
\]</span>
Procedemos con las modificaciones en la tabla de datos, para transformar el modelo en un caso lineal:</p>
<p>Según la transformación recomendada y adaptada a esta variante del modelo, se debe hacer los siguientes cambios de variable: <span class="math inline">\(X_2 = \ln(x), Y_2 = \ln(y-3), b_0 = \ln(1) = 0, b_1 = \beta\)</span> para luego suministrarle estos valores a la función <code>lm</code> de R para crear una <code>MRLS</code>. Note que en este caso como <span class="math inline">\(b_0 = 0\)</span> se concluye que el modelo pasa por el origen, es decir, por el punto <span class="math inline">\((0,0)\)</span> y eso se verá reflejado en la nueva tabla como se muestra a continuación:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="regresion-no-lineal-simple.html#cb250-1" tabindex="-1"></a><span class="co"># Se modifican los datos de la tabla original</span></span>
<span id="cb250-2"><a href="regresion-no-lineal-simple.html#cb250-2" tabindex="-1"></a>X2 <span class="ot">&lt;-</span> <span class="fu">log</span>(X)</span>
<span id="cb250-3"><a href="regresion-no-lineal-simple.html#cb250-3" tabindex="-1"></a>Y2 <span class="ot">&lt;-</span> <span class="fu">log</span>(Y<span class="dv">-3</span>)</span>
<span id="cb250-4"><a href="regresion-no-lineal-simple.html#cb250-4" tabindex="-1"></a>datos4 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X2, Y2)</span>
<span id="cb250-5"><a href="regresion-no-lineal-simple.html#cb250-5" tabindex="-1"></a>datos4.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datos4)</span>
<span id="cb250-6"><a href="regresion-no-lineal-simple.html#cb250-6" tabindex="-1"></a>modelolm <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y2 <span class="sc">~</span> <span class="dv">0</span> <span class="sc">+</span> X2, <span class="at">data =</span> datos4.df) <span class="co">#Intercepto igual a cero</span></span>
<span id="cb250-7"><a href="regresion-no-lineal-simple.html#cb250-7" tabindex="-1"></a>modelolm</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Y2 ~ 0 + X2, data = datos4.df)
## 
## Coefficients:
##    X2  
## 2.024</code></pre>
<p>Del modelo anterior se tiene que:
<span class="math display">\[
\beta = 2.024
\]</span>
Por lo que haciendo nuevamente la transformación, el modelo buscado sería:
<span class="math display">\[
y = 3 + x^{2.024}
\]</span>
Los siguiente códigos ayudarán a mostrar gráficamente el modelo obtenido con respecto a los datos del gráfico de dispersión:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="regresion-no-lineal-simple.html#cb252-1" tabindex="-1"></a><span class="co"># Se genera una secuencia de puntos, para simular continuidad en la gráfica</span></span>
<span id="cb252-2"><a href="regresion-no-lineal-simple.html#cb252-2" tabindex="-1"></a>X</span></code></pre></div>
<pre><code>## [1] 1 2 4 6</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="regresion-no-lineal-simple.html#cb254-1" tabindex="-1"></a>Y</span></code></pre></div>
<pre><code>## [1]  4  7 20 40</code></pre>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="regresion-no-lineal-simple.html#cb256-1" tabindex="-1"></a>xo <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(X), <span class="at">to =</span> <span class="fu">max</span>(X) , <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb256-2"><a href="regresion-no-lineal-simple.html#cb256-2" tabindex="-1"></a>yo <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">+</span> xo<span class="sc">^</span><span class="fl">2.024</span></span>
<span id="cb256-3"><a href="regresion-no-lineal-simple.html#cb256-3" tabindex="-1"></a></span>
<span id="cb256-4"><a href="regresion-no-lineal-simple.html#cb256-4" tabindex="-1"></a><span class="co"># Graficamos dispersión y el modelo de ajuste en un mismo plot</span></span>
<span id="cb256-5"><a href="regresion-no-lineal-simple.html#cb256-5" tabindex="-1"></a><span class="fu">plot</span>(X,Y, <span class="at">main =</span> <span class="st">&quot;Modelo de RNLS f(x)=3 + x^2.024&quot;</span>, <span class="at">col =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb256-6"><a href="regresion-no-lineal-simple.html#cb256-6" tabindex="-1"></a><span class="fu">lines</span>(xo, yo, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-67-1.png" width="672" /></p>
<p>Otra opción para el gráfico es usar ggplot2, como se muestra en el siguente código:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="regresion-no-lineal-simple.html#cb257-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y, xo, yo) <span class="co"># se juntan las columnas</span></span></code></pre></div>
<pre><code>## Warning in cbind(X, Y, xo, yo): number of rows of result is not a multiple of
## vector length (arg 1)</code></pre>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="regresion-no-lineal-simple.html#cb259-1" tabindex="-1"></a>data.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(data) <span class="co"># se crea un objeto dataframe</span></span>
<span id="cb259-2"><a href="regresion-no-lineal-simple.html#cb259-2" tabindex="-1"></a><span class="fu">names</span>(data.df) <span class="co"># verificamos los nombres de las columnas</span></span></code></pre></div>
<pre><code>## [1] &quot;X&quot;  &quot;Y&quot;  &quot;xo&quot; &quot;yo&quot;</code></pre>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="regresion-no-lineal-simple.html#cb261-1" tabindex="-1"></a><span class="co"># Se crea un gráfico de dispersión para ver de manera exporatoria los datos y se sobrepone el modelo de RNLS que encontramos f(x)=3 + x^2.02569. Note que dentro de las opciones, para dar un mejor acabado al gráfico, se limita el intervalo de &quot;x&quot; e &quot;y&quot;</span></span>
<span id="cb261-2"><a href="regresion-no-lineal-simple.html#cb261-2" tabindex="-1"></a></span>
<span id="cb261-3"><a href="regresion-no-lineal-simple.html#cb261-3" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(data.df, <span class="fu">aes</span>(X, Y, <span class="at">xmin =</span> <span class="dv">0</span>, <span class="at">xmax =</span> <span class="dv">7</span>, <span class="at">ymin =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">ymax =</span> <span class="dv">50</span></span>
<span id="cb261-4"><a href="regresion-no-lineal-simple.html#cb261-4" tabindex="-1"></a>))</span>
<span id="cb261-5"><a href="regresion-no-lineal-simple.html#cb261-5" tabindex="-1"></a>g3 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">stroke =</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> xo, <span class="at">y =</span> yo), <span class="at">colour =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb261-6"><a href="regresion-no-lineal-simple.html#cb261-6" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;Modelo RNLS&quot;</span>)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
<p>Tome en cuenta que los vectores <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son más pequeños que los vectores <span class="math inline">\(Xo\)</span> y <span class="math inline">\(Yo\)</span> que fueron creados solamente con fines estéticos de la graficación, entonces, R se encarga de equilibrar en dimensión los vectores generando secuencias repqedidas de los vectores más <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> hasta completar las filas, pero, sin alterar los pares ordenados originales.</p>
<p>Seguidamente a manera de ilustración, se muestran las tablas:</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="regresion-no-lineal-simple.html#cb262-1" tabindex="-1"></a><span class="fu">head</span>(datos.df)</span></code></pre></div>
<pre><code>##      X   Y
## 1 18.0  19
## 2 19.0  40
## 3 19.5  79
## 4 19.7 130
## 5 19.9 397</code></pre>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="regresion-no-lineal-simple.html#cb264-1" tabindex="-1"></a><span class="fu">head</span>(data.df, <span class="dv">15</span>)</span></code></pre></div>
<pre><code>##    X  Y    xo       yo
## 1  1  4 1.000 4.000000
## 2  2  7 1.001 4.002025
## 3  4 20 1.002 4.004052
## 4  6 40 1.003 4.006081
## 5  1  4 1.004 4.008113
## 6  2  7 1.005 4.010146
## 7  4 20 1.006 4.012181
## 8  6 40 1.007 4.014219
## 9  1  4 1.008 4.016258
## 10 2  7 1.009 4.018300
## 11 4 20 1.010 4.020344
## 12 6 40 1.011 4.022389
## 13 1  4 1.012 4.024437
## 14 2  7 1.013 4.026487
## 15 4 20 1.014 4.028539</code></pre>
<p>Seguidamente se determina el IC para los parámetros <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="regresion-no-lineal-simple.html#cb266-1" tabindex="-1"></a><span class="fu">confint</span>(<span class="fu">lm</span>(Y2 <span class="sc">~</span> X2, <span class="at">data =</span> datos2.df),<span class="at">level =</span> <span class="fl">0.95</span>)</span></code></pre></div>
<pre><code>##                  2.5 %    97.5 %
## (Intercept) -0.4781531 -0.461396
## X2           9.2425203  9.563962</code></pre>
<p>Nota: El IC que de obtiene para los estimadores de los parámetros a partir de la función <code>lm</code>, no siempre pueden ser generalizados a los modelos no lineales.</p>
<p>Por ejemplo, para el caso de los modelos exponenciales, como los parámetors <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>sufren una transformacióm al linealizar el modelo, respectivamente por <span class="math inline">\(\ln(b_0)\)</span> y <span class="math inline">\(\ln(b_1)\)</span>, hacen que los Intervalos de Confianza que se obtienen a partir de la función <code>lm</code>no se puedan extrapolar o aplicar para <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="regresion-no-lineal-simple.html#cb268-1" tabindex="-1"></a>datosnlm2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y) </span>
<span id="cb268-2"><a href="regresion-no-lineal-simple.html#cb268-2" tabindex="-1"></a>datosnlm2.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datosnlm2)</span>
<span id="cb268-3"><a href="regresion-no-lineal-simple.html#cb268-3" tabindex="-1"></a>datosnlm2.df</span></code></pre></div>
<pre><code>##   X  Y
## 1 1  4
## 2 2  7
## 3 4 20
## 4 6 40</code></pre>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="regresion-no-lineal-simple.html#cb270-1" tabindex="-1"></a>modelolm2 <span class="ot">&lt;-</span> <span class="fu">nls</span>(Y <span class="sc">~</span> <span class="dv">3</span> <span class="sc">+</span> X<span class="sc">^</span>b, <span class="at">data =</span> datosnlm2.df, <span class="at">start =</span> <span class="fu">list</span>( <span class="at">b =</span> <span class="dv">1</span>))</span>
<span id="cb270-2"><a href="regresion-no-lineal-simple.html#cb270-2" tabindex="-1"></a>modelolm2</span></code></pre></div>
<pre><code>## Nonlinear regression model
##   model: Y ~ 3 + X^b
##    data: datosnlm2.df
##     b 
## 2.018 
##  residual sum-of-squares: 0.3894
## 
## Number of iterations to convergence: 5 
## Achieved convergence tolerance: 9.931e-06</code></pre>
<p>Grafiquemos el modelo:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="regresion-no-lineal-simple.html#cb272-1" tabindex="-1"></a>xo <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fu">min</span>(X), <span class="at">to =</span> <span class="fu">max</span>(X) , <span class="at">by =</span> <span class="fl">0.001</span>)</span>
<span id="cb272-2"><a href="regresion-no-lineal-simple.html#cb272-2" tabindex="-1"></a>yo <span class="ot">&lt;-</span> <span class="dv">3</span> <span class="sc">+</span> xo<span class="sc">^</span><span class="fl">2.018</span></span>
<span id="cb272-3"><a href="regresion-no-lineal-simple.html#cb272-3" tabindex="-1"></a></span>
<span id="cb272-4"><a href="regresion-no-lineal-simple.html#cb272-4" tabindex="-1"></a>datanlm2 <span class="ot">&lt;-</span> <span class="fu">cbind</span>(X, Y, xo, yo) <span class="co"># se juntan las columnas</span></span></code></pre></div>
<pre><code>## Warning in cbind(X, Y, xo, yo): number of rows of result is not a multiple of
## vector length (arg 1)</code></pre>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb274-1"><a href="regresion-no-lineal-simple.html#cb274-1" tabindex="-1"></a>datanlm2.df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(datanlm2) <span class="co"># se crea un objeto dataframe</span></span>
<span id="cb274-2"><a href="regresion-no-lineal-simple.html#cb274-2" tabindex="-1"></a><span class="fu">names</span>(datanlm2.df) <span class="co"># verificamos los nombres de las columnas</span></span></code></pre></div>
<pre><code>## [1] &quot;X&quot;  &quot;Y&quot;  &quot;xo&quot; &quot;yo&quot;</code></pre>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="regresion-no-lineal-simple.html#cb276-1" tabindex="-1"></a>g3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(datanlm2.df, <span class="fu">aes</span>(X, Y, <span class="at">xmin =</span> <span class="dv">0</span>, <span class="at">xmax =</span> <span class="dv">7</span>, <span class="at">ymin =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">ymax =</span><span class="dv">50</span> ))</span>
<span id="cb276-2"><a href="regresion-no-lineal-simple.html#cb276-2" tabindex="-1"></a>g3 <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">fill =</span> <span class="st">&quot;red&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">stroke =</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> xo, <span class="at">y =</span> yo), <span class="at">colour =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb276-3"><a href="regresion-no-lineal-simple.html#cb276-3" tabindex="-1"></a> <span class="fu">labs</span>(<span class="at">colour =</span> <span class="st">&quot;Modelo RNLS&quot;</span>)</span></code></pre></div>
<p><img src="Compendio-Estad%C3%ADstica_files/figure-html/unnamed-chunk-72-1.png" width="672" /></p>
<p>A manera de práctica, se comparten los siguientes ejercicios:</p>
<p><strong>Ejercicio 49</strong></p>
<p>Considere los datos en la siguiente tabla:</p>
<table>
<thead>
<tr class="header">
<th align="center"><span class="math inline">\(X\)</span></th>
<th align="center">0</th>
<th align="center">4</th>
<th align="center">5</th>
<th align="center">6</th>
<th align="center">7</th>
<th align="center">8</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center"><span class="math inline">\(Y\)</span></td>
<td align="center">2</td>
<td align="center">37</td>
<td align="center">80</td>
<td align="center">172</td>
<td align="center">360</td>
<td align="center">756</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li><p>Escoja y justifique un modelo de regresión para y como función de x. R/ Exponencial</p></li>
<li><p>Encuentre una ecuación de regresión para el modelo escogido. R/ <span class="math inline">\(y = 1.9648 \; (2.10265)^x\)</span></p></li>
</ol>
<p><strong>Ejercicio 50</strong></p>
<p>Los siguientes datos, que representan las velocidades promedio para las diferentes distancias de cinco corredores, todos con mas de 70 años de edad:</p>
<table>
<thead>
<tr class="header">
<th align="center">Distancia <span class="math inline">\((d)\)</span></th>
<th align="center">1.6</th>
<th align="center">3</th>
<th align="center">5</th>
<th align="center">10</th>
<th align="center">42</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">Vel. prom. <span class="math inline">\((V)\)</span></td>
<td align="center">4.7</td>
<td align="center">4.2</td>
<td align="center">4.1</td>
<td align="center">3.9</td>
<td align="center">3.8</td>
</tr>
</tbody>
</table>
<ol style="list-style-type: decimal">
<li><p>Determine la ecuación de regresión no lineal simple (potencial) de <span class="math inline">\(v\)</span> en función de <span class="math inline">\(d\)</span>. <br>
R/ <span class="math inline">\(v = 4.604d^{-0.05}\)</span></p></li>
<li><p>Determine un IC del <span class="math inline">\(95\%\)</span> para <span class="math inline">\(\alpha \; (v=ad^\beta, \; \text{asuma las hipótesis de regresión})\)</span>. <br>
R/ <span class="math inline">\(]4.10688482, \; 5.16208568[\)</span></p></li>
</ol>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="regresion-y-correlacion-lineal.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regresion-lineal-multiple.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
